.TH VIMDIFF 1 "30 marzo 2001"
.SH NOME
vimdiff \- modifica due, tre o quattro versioni di un file con Vim,
visualizzando le differenze
.SH SINTASSI
.br
.B vimdiff
[opzioni] file1 file2 [file3 [file4]]
.PP
.B gvimdiff
.SH DESCRIZIONE
.B Vimdiff
inizia
.B Vim
per due (o tre o quattro) file.
Ogni file ha una sua finestra.
Le differenze fra file sono evidenziate.
È una maniera elegante per controllare modifiche e portare modifiche
verso un'altra versione dello stesso file.
.PP
Vedere vim(1) per dettagli su Vim in generale.
.PP
Se iniziato con
.B gvimdiff
la GUI sarà utilizzata, se disponibile.
.PP
In ogni finestra l'opzione 'diff' è impostata, evidenziando così le
differenze.
.br
Le opzioni 'wrap' e 'scrollbind' sono impostate per migliorare la
visibilità del testo.
.br
L'opzione 'foldmethod' è impostata al valore "diff", che mette gruppi di
linee uguali fra i diversi file in una piegatura. 'foldcolumn' è impostato
a due per poter facilmente visualizzare le piegature, aprirle e chiuderle.
.SH OPZIONI
Lo schermo è diviso verticalmente, come se aveste usato l'opzione "\-O".
Per dividerlo orizzontalmente, usare l'opzione "\-o".
.PP
Per tutte le altre opzioni, vedere vim(1).
.SH VEDERE ANCHE
vim(1)
.SH AUTORE
Buona parte di
.B Vim
è stato scritto da Bram Moolenaar, con molto aiuto da altri.
Vedere ":help credits" in
.B Vim.
