.Dd May 13, 2015
.Dt NVIMTUTOR 1
.Os Neovim
.Sh NAME
.Nm nvimtutor
.Nd Neovim tutor
.Sh SYNOPSIS
.Nm
.Op Ar language
.Sh DESCRIPTION
.Nm
starts an interactive tutorial meant to teach the basics of
.Xr vim 1 .
The optional
.Ar language
argument is the two-letter name of a language,
such as
.Sy it
or
.Sy es .
If
.Ar language
is omitted, the language dictated by the current locale is used.
If a tutorial for
.Ar language
isn't available, the English tutorial will be used.
.Sh SEE ALSO
.Xr nvim 1
.Sh AUTHORS
Vimtutor was originally written for
.Xr vi 1
by
.An -nosplit
.An Michael C. Pierce
and
.An Robert K. Ware ,
Colorado School of Mines, using ideas supplied by
.An Charles Smith Aq Mt bware@mines.colorado.edua .
.Pp
It was modified for
.Xr vim 1
by
.An Bram Moolenaar .
See the tutor files for the names of the individual translators.
