.Dd May 5, 2015
.Dt NVIM 1 Neovim
.Os Neovim
.Sh NAME
.Nm nvim
.Nd extensible modal text editor
.Sh SYNOPSIS
.Nm
.Op Ar options
.Op Ar file ...
.Nm
.Op Ar options
.Fl
.Nm
.Op Ar options
.Fl t Ar tag
.Nm
.Op Ar options
.Fl q Ar errorfile
.Sh DESCRIPTION
.Nm
is an extensible text editor based on
.Xr vim 1 .
.Pp
While running
.Nm ,
consult the on-line help system with the
.Ic :help
command.
If no files are specified
.Nm
will start with an empty buffer.
Otherwise, one out of the following four may be used to choose one or more
files to be edited.
.Bl -tag -width Fl
.It Ar file ...
File(s) to edit.
The first one will be the current file and read into the buffer, where the
cursor will be position on the first line.
To switch to the other files use the
.Ic :next
command.
.It Fl
The text to edit is read from standard input.
Commands are read from standard error, which should be a terminal.
.It Fl t Ar tag
The file to edit and the initial cursor position depends on a
tag, a sort of goto label.
.Ar tag
is looked up in the tags file, the associated file becomes the current
file and the associated command is executed.
If
.Ar tag
is a function name, the file containing that function is opened
with the cursor positioned at the start of the function.
See
.Ic :help tag-commands .
.It Fl q Ar errorfile
QuickFix mode.
.Ar errorfile
is read and the first error is displayed.
If
.Ar errorfile
is omitted, the filename is obtained from the 'errorfile'
option (defaults to
.Pa errors.err ) .
Further errors can be jumped to with the
.Ic :cn
command. See
.Ic :help quickfix .
.It There are a number of other options:
.It Fl -
Interpret all further arguments as files.
This can be used to edit files starting with a hyphen.
.It Cm + Ns Op Ar num
For the first file, position the cursor on line
.Ar num .
If
.Ar num
is not provided, position the cursor on the last line.
.It Cm +/ Ns Op Ar pat
For the first file, position the cursor on the first occurrence of
.Ar pat .
See
.Ic :help search-pattern
for the available search patterns.
.It Fl S Op Ar file
Source
.Ar file
after the first file argument has been read.
This is equivalent to
.Ic -c \(dqsource file\(dq .
.Ar file
cannot start with a hyphen.
If
.Ar file
is omitted, then
.Pa Session.vim
is used (only works if
.Fl S
is the last argument provided).
.It Fl c Ar command
.Ar command
is an Ex command to be executed after the first file has been read.
Up to 10 instances of
.Fl c
or
.Cm +
can be used.
.It Fl -cmd Ar command
Like
.Fl c ,
but execute
.Ar command
just before processing an nvimrc.
Up to 10 instances of these can be used, independently from instances of
.Fl c .
.It Fl D
Debugging mode.
Started when executing the first command from a script.
.It Fl e
Ex mode.
.It Fl E
Improved Ex mode.
.It Fl d
Diff mode.
Shows the difference between up to four files.
.It Fl l
Lisp mode; sets the options 'lisp' and 'showmatch'.
.It Fl b
Binary mode; sets the options that make it possible to edit binaries.
.It Fl A
Arabic mode; sets the option 'arabic'.
.It Fl F
Farsi mode; sets the options 'fkmap' and 'rightleft'.
.It Fl H
Hebrew mode; sets the options 'hkmap' and 'rightleft'.
.It Fl m
Disable file modifications; sets the option 'write'.
Writing to a file is disabled, but buffers can still be modified.
.It Fl M
.\" find a macro for use with the options (probably not .Ic), so that they aren't
.\" subject to being split by line breaks.
Disable file and buffer modifications; sets the options 'modifiable' and 'write'.
Note that these options can be set to re-enable making modifications.
.It Fl n
Disable the use of swap files; sets the option 'updatecount' to 0.
This can be useful for editing file(s) on a slow medium.
.It Fl Z
Restricted mode.
Disable commands that make use of an external shell.
.It Fl R
Read-only mode; sets the option 'readonly'; implies
.Fl n .
Buffers can still be edited, but cannot be written to disk if already
associated with a file.
To overwrite a file, add an exclamation mark to the needed Ex command, such
as
.Ic :w! .
See
.Ic :help 'readonly' .
.It Fl o Ns Op Ar N
Open
.Ar N
windows stacked horizontally.
If
.Ar N
is omitted, open one window for each file.
.It Fl O Ns Op Ar N
Open
.Ar N
windows stacked vertically.
If
.Ar N
is omitted, open one window for each file.
.It Fl p Ns Op Ar N
Open
.Ar N
tab pages.
If
.Ar N
is omitted, open one tab page for each file.
.It Fl r , L
List swap files with information about using them for recovery.
.It Fl r Op Ar file
Recovery mode.
The swap file
.Ar file
is used to recover a crashed session.
The swap file has the same filename as the text file, but with ".swp" appended.
See
.Ic :help recovery .
.It Fl s
Silent mode.
Only takes effect if
.Fl e
is provided before
.Fl s .
.It Fl s Ar scriptin
The file
.Ar scriptin
is read.
The characters in the file are interpreted as if they had been typed.
The same can be done with the command
.Ic :source! scriptin .
If the end of the file is reached before
.Nm
exits, further characters
are read from the keyboard.
.It Fl i Ar nviminfo
Use
.Ar nviminfo
instead of the default of
.Pa ~/.nviminfo .
Use
.Sy -i NONE
to not use an nviminfo file.
.It Fl u Ar nvimrc
Use
.Ar nvimrc
instead of the default of
.Pa ~/.nvimrc .
Use
.Sy -u NONE
to not use an nvimrc file.
To skip all initializations, use
.Sy -u NONE .
See
.Ic :help initialization .
.It Fl V Ns Op Ar N
Verbose.
Print messages about which files are being sourced and for reading and
writing an nviminfo file.
.Ar N
is the value for the 'verbose' option; defaults to 10 if not provided.
.It Fl w Ar scriptout
Append all typed characters to
.Ar scriptout .
This can be used for creating a script to be used with
.Fl s
or
.Ic :source! .
.It Fl W Ar scriptout
Like
.Fl w ,
but truncate
.Ar scriptout .
.It Fl -literal
Interpret filenames literally, that is do not expand wildcards.
This has no effect on UNIX-like systems, where the shell expands wildcards.
.It Fl -noplugin
Skip loading plugins; implied by
.Fl u Ar NONE .
.It Fl h , -help
Print a help message and exit.
.It Fl v , -version
Print version information and exit.
.El
.Sh ENVIRONMENT
.Bl -tag -width Ev
.It Ev VIMINIT
todo
.It Ev VIM
Used to locate various user files, such as the user nvimrc.
.It Ev VIMRUNTIME
Used to locate runtime files, such as on-line documentation and
syntax highlighting definitions.
.It Ev SHELL
Used to set the 'shell' option, which determines the shell used by the
.Ic :terminal
command.
.It Ev NVIM_TUI_CURSOR_SHAPE
todo
.It Ev NVIM_TUI_TRUE_COLOR
todo
.El
.Sh FILES
.Bl -tag -width Pa
.It Pa ~/.nvimrc , ~/.nvim/nvimrc
The user-local
.Nm
configuration file.
.It Pa ~/.nvim
The user-local
.Nm
runtime directory.
.It Pa /etc/nvim/nvimrc
The system-global
.Nm
configuration file.
.It Pa /usr/share/nvim
The system-global
.Nm
runtime directory.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr nvimtutor 1
.Sh AUTHORS
Most of
.Xr vim 1
was written by
.An -nosplit
.An Bram Moolenaar ,
with a lot of help from others.
See
.Ic :help credits .
.Pp
Although hardly any of the original code remains,
.Xr vim 1
is based on Stevie, worked on by
.An Tim Thompson ,
.An Tony Andrews ,
and
.An G.R. (Fred) Walter .
