name: 'setup'
description: "Creates necessary setup for CI"
inputs:
  install_flags:
    description: 'Install script flags'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Set $BIN_DIR
      shell: bash
      run: echo "$BIN_DIR" >> $GITHUB_PATH # zizmor: ignore[github-env]

    - if: ${{ runner.os != 'Windows' }}
      name: Set ulimit
      shell: bash
      run: ulimit -c unlimited

    - if: ${{ runner.os == 'Windows' }}
      run: .github/scripts/env.ps1
      shell: pwsh

    - name: Install dependencies
      env:
        INSTALL_FLAGS: ${{ inputs.install_flags }}
      run: ./.github/scripts/install_deps.sh ${INSTALL_FLAGS}
      shell: bash

    - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
      with:
        version: 0.15.2

    - name: Cache
      uses: ./.github/actions/cache
