env:
  CIRRUS_CLONE_DEPTH: '2'
  LANG: en_US.UTF-8

freebsd_task:
  name: FreeBSD
  only_if: $BRANCH != "master"
  freebsd_instance:
    image_family: freebsd-13-1
  timeout_in: 30m
  install_script:
    - pkg update -f
    - pkg install -y cmake gmake ninja pkgconf unzip wget gettext python libffi git
  build_deps_script:
    - gmake deps
  build_script:
    - gmake CMAKE_EXTRA_FLAGS="-DCI_BUILD=ON" nvim
  workaround_script:
    # Run tests as user "cirrus" instead of root. This is required for the
    # permission-related tests to work correctly.
    - pw useradd cirrus -m
    - chown -R cirrus:cirrus .
  functionaltest_script:
    - sudo -u cirrus gmake functionaltest
  unittest_script:
    - sudo -u cirrus gmake unittest
  oldtest_script:
    - sudo -u cirrus gmake oldtest

with_external_deps_task:
  container:
    dockerfile: ci/Dockerfile.external_deps
  deps_script:
      # Ideally all dependencies should external for this job, but some
      # dependencies don't have the required version available. We use the
      # bundled versions for these with the hopes of being able to remove them
      # later on.
    - cmake -S cmake.deps -B .deps -G Ninja -D USE_BUNDLED=OFF -D USE_BUNDLED_LIBVTERM=ON -D USE_BUNDLED_TS=ON
    - cmake --build .deps
  build_script:
    - cmake --preset ci
    - cmake --build build
