env:
  CIRRUS_CLONE_DEPTH: '2'
  LANG: en_US.UTF-8

freebsd_task:
  name: FreeBSD
  only_if: $BRANCH != "master"
  freebsd_instance:
    image_family: freebsd-13-2
  timeout_in: 30m
  install_script:
    - pkg install -y cmake gmake ninja unzip wget gettext python git
  build_deps_script:
    - gmake deps
  build_script:
    - gmake CMAKE_EXTRA_FLAGS="-DCI_BUILD=ON" nvim
  workaround_script:
    # Run tests as user "cirrus" instead of root. This is required for the
    # permission-related tests to work correctly.
    - pw useradd cirrus -m
    - chown -R cirrus:cirrus .
  always:
    unittest_script:
      - sudo -u cirrus gmake unittest
    functionaltest_script:
      - sudo -u cirrus gmake functionaltest
    oldtest_script:
      - sudo -u cirrus gmake oldtest

macos_task:
  name: macOS M1
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest
  env:
    CC: clang
  timeout_in: 30m
  install_script:
    - brew update
    - brew install cpanminus ninja
  build_deps_script:
    - cmake -S cmake.deps -B .deps -G Ninja
    - cmake --build .deps
  build_script:
    - cmake --preset ci
    - cmake --build build
  always:
    unittest_script:
      - make unittest
    functionaltest_script:
      - make functionaltest
    oldtest_script:
      - make oldtest
