# Alternative settings for special snowflakes like: decorations_spec.lua, multigrid_spec.lua, etc.

column_width = 140
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferSingle"
call_parentheses = "Input"
