codecov:
  notify:
    require_ci_to_pass: no
  ci:
    - appveyor
    - travis
    - !neovim-qb.szakmeister.net

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment: off
