.TH EVIM 1 "2002 February 16"
.SH NAME
evim \- easy Vim, edit a file with Vim and setup for modeless editing
.SH SYNOPSIS
.br
.B evim
[options] [file ..]
.br
.B eview
.SH DESCRIPTION
.B eVim
starts
.B Vim
and sets options to make it behave like a modeless editor.
This is still Vim but used as a point-and-click editor.
This feels a lot like using Notepad on MS-Windows.
.B eVim
will always run in the GUI, to enable the use of menus and toolbar.
.PP
Only to be used for people who really can't work with Vim in the normal way.
Editing will be much less efficient.
.PP
.B eview
is the same, but starts in read-only mode.  It works just like evim \-R.
.PP
See vim(1) for details about Vim, options, etc.
.PP
The 'insertmode' option is set to be able to type text directly.
.br
Mappings are setup to make Copy and Paste work with the MS-Windows keys.
CTRL-X cuts text, CTRL-C copies text and CTRL-V pastes text.
Use CTRL-Q to obtain the original meaning of CTRL-V.
.SH OPTIONS
See vim(1).
.SH FILES
.TP 15
/usr/local/lib/vim/evim.vim
The script loaded to initialize eVim.
.SH AKA
Also Known As "Vim for gumbies".
When using evim you are expected to take a handkerchief,
make a knot in each corner and wear it on your head.
.SH SEE ALSO
vim(1)
.SH AUTHOR
Most of
.B Vim
was made by Bram Moolenaar, with a lot of help from others.
See the Help/Credits menu.
