.TH VIMDIFF 1 "2001 March 30"
.SH NAME
vimdiff \- edit two, three or four versions of a file with Vim and show differences
.SH SYNOPSIS
.br
.B vimdiff
[options] file1 file2 [file3 [file4]]
.PP
.B gvimdiff
.SH DESCRIPTION
.B Vimdiff
starts
.B Vim
on two (or three or four) files.
Each file gets its own window.
The differences between the files are highlighted.
This is a nice way to inspect changes and to move changes from one version
to another version of the same file.
.PP
See vim(1) for details about Vim itself.
.PP
When started as
.B gvimdiff
the GUI will be started, if available.
.PP
In each window the 'diff' option will be set, which causes the differences
to be highlighted.
.br
The 'wrap' and 'scrollbind' options are set to make the text look good.
.br
The 'foldmethod' option is set to "diff", which puts ranges of lines without
changes in a fold.  'foldcolumn' is set to two to make it easy to spot the
folds and open or close them.
.SH OPTIONS
Vertical splits are used to align the lines, as if the "\-O" argument was used.
To use horizontal splits instead, use the "\-o" argument.
.PP
For all other arguments see vim(1).
.SH SEE ALSO
vim(1)
.SH AUTHOR
Most of
.B Vim
was made by Bram Moolenaar, with a lot of help from others.
See ":help credits" in
.B Vim.
