#!/bin/sh
set -e

if [ "$1" = "remove" ]; then
  update-alternatives --remove vi /usr/bin/nvim
  update-alternatives --remove vim /usr/bin/nvim
  update-alternatives --remove view /usr/bin/nvim
fi

exit 0
