.TH VIMTUTOR 1 "2001 Kwi 2"
.SH NAZWA
vimtutor \- nauczyciel Vima
.SH SYNOPSIS
.br
.B vimtutor -g [język]
.SH OPIS
.B Vimtutor
uruchamia nauczyciela
.B Vima.
Najpierw kopiuje właściwy plik, dzięki temu można go zmieniać bez obaw
utraty treści.
.PP
.B Vimtutor
przyda się ludziom, którzy chcą się nauczyć pierwszych poleceń
.B Vima
.PP
Opcjonalny argument \-g uruchamia vimtutor w gvimie a nie w Vimie jeśli
graficzna wersja Vima jest dostępna, jeśli nie zostanie uruchomiony Vim.
.PP
Opcjonalny argument [język] jest dwu literowym kodem języka, tak jak
"it" lub "es".
Jeśli brak argumentu [język] zostanie użyty język bieżącej
lokalizacji.
Jeśli nauczyciel w tym języku jest dostępny, zostanie użyty \- w innym
wypadku zostanie wykorzystana wersja angielska.
.PP
.B Vim
jest uruchamiany zawsze w trybie kompatybilności z Vi
.SH PLIKI
.TP 15
/usr/local/lib/vim/tutor/tutor[.język]
Tekstowe pliki
.B Vimtutora.
.TP 15
/usr/local/lib/vim/tutor/tutor.vim
Skrypt Vima używany do kopiowania pliku
.B Vimtutora.
.SH AUTOR
.B Vimtutor
został początkowo napisany dla Vi przez Michaela C. Pierce'a
i Roberta K. Ware'a z Colorado School of Mines zainspirowani przez
Charlesa Smitha z Colorado State University.
E-mail: bware@mines.colorado.edu
.br
Zmodyfikowany na potrzeby
.B Vima
przez Brama Moolenaara.
Nazwiska tłumaczy w plikach.
.SH ZOBACZ TAKŻE
vim(1)
