local t = require('test.testutil')

local eq = t.eq
local matches = t.matches

setup(function()
  if not vim.async then
    vim.async = require('vim.async')
  end
end)

describe('vim.async', function()
  describe('RingQueue', function()
    it('push and pop', function()
      local q = vim.async.ringqueue(3)
      eq(true, q:push('a'))
      eq(true, q:push('b'))
      eq('a', q:pop())
      eq('b', q:pop())
      eq(nil, q:pop())
    end)

    it('rejects push when full', function()
      local q = vim.async.ringqueue(2)
      q:push(1)
      q:push(2)
      eq(true, q:is_full())
      eq(false, q:push(3))
    end)

    it('wraps around the ring buffer', function()
      local q = vim.async.ringqueue(3)
      q:push(1)
      q:push(2)
      q:push(3)
      eq(1, q:pop())
      eq(2, q:pop())
      eq(true, q:push(4))
      eq(true, q:push(5))
      eq(3, q:pop())
      eq(4, q:pop())
      eq(5, q:pop())
    end)

    it('is_empty returns true initially and after draining', function()
      local q = vim.async.ringqueue(3)
      eq(true, q:is_empty())
      q:push('x')
      eq(false, q:is_empty())
      q:pop()
      eq(true, q:is_empty())
    end)
  end)

  describe('ListQueue', function()
    it('push and pop', function()
      local q = vim.async.listqueue()
      q:push(1)
      q:push(2)
      q:push(3)
      eq(1, q:pop())
      eq(2, q:pop())
      eq(3, q:pop())
      eq(nil, q:pop())
    end)

    it('is_empty', function()
      local q = vim.async.listqueue()
      eq(true, q:is_empty())
      q:push(42)
      eq(false, q:is_empty())
      q:pop()
      eq(true, q:is_empty())
    end)
  end)

  describe('chan', function()
    it('send and recv', function()
      local chan = vim.async.chan(5)
      vim.async.spawn(function() chan:send(42) end)
      eq(42, chan:recv())
    end)

    it('send and recv multiple messages', function()
      local chan = vim.async.chan(10)
      vim.async.spawn(function()
        chan:send(1)
        chan:send(2)
        chan:send(3)
      end)
      eq(1, chan:recv())
      eq(2, chan:recv())
      eq(3, chan:recv())
    end)

    it('close wakes blocked sender', function()
      local chan = vim.async.chan(1)
      chan:send('a')
      local ok = false
      vim.async.spawn(function()
        chan:send('b')
        ok = true
      end)
      vim.wait(50, function() return ok end)
      eq(false, ok)
      eq(true, chan:close())
    end)

    it('close returns false when already closed', function()
      local chan = vim.async.chan(1)
      eq(true, chan:close())
      eq(false, chan:close())
    end)

    it('send on closed channel errors', function()
      local chan = vim.async.chan(1)
      chan:close()
      local stat, err = pcall(chan.send, chan, 'x')
      eq(false, stat)
      matches('Send on closed channel', err)
    end)

    it('is_closed', function()
      local chan = vim.async.chan(1)
      eq(false, chan:is_closed())
      chan:close()
      eq(true, chan:is_closed())
    end)
  end)

  describe('spawn', function()
    it('executes a function', function()
      local ran = false
      vim.async.spawn(function() ran = true end)
      vim.wait(100, function() return ran end)
      eq(true, ran)
    end)

    it('forwards arguments', function()
      local result
      vim.async.spawn(function(a, b) result = a + b end, 3, 4)
      vim.wait(100, function() return result ~= nil end)
      eq(7, result)
    end)
  end)

  describe('await', function()
    it('returns callback results synchronously', function()
      local result = vim.async.await(function(cb) cb('hello') end)
      eq('hello', result)
    end)

    it('forwards arguments to func', function()
      local result = vim.async.await(function(a, b, cb) cb(a + b) end, 3, 4)
      eq(7, result)
    end)

    it('handles multiple return values', function()
      local a, b, c = vim.async.await(function(cb) cb(1, 2, 3) end)
      eq(1, a)
      eq(2, b)
      eq(3, c)
    end)
  end)
end)
