name: 'Install dependencies'
description: "This action installs required dependencies."
inputs:
  type:
    description: 'Type of installation'
  additional_packages:
    description: 'Additional packages to install'
runs:
  using: "composite"
  steps:
    - if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y $DEPENDENCIES ${{ inputs.additional_packages }}
      env:
        DEPENDENCIES: |
          autoconf
          automake
          build-essential
          cmake
          curl
          gettext
          libtool-bin
          locales-all
          ninja-build
          pkg-config
          unzip
      shell: bash

    - if: runner.os == 'Linux' && inputs.type == 'system'
      run: |
        sudo add-apt-repository ppa:neovim-ppa/stable
        sudo apt-get update
        sudo apt-get install -y $DEPENDENCIES
      env:
        DEPENDENCIES: |
          libluajit-5.1-dev
          libmsgpack-dev
          libtermkey-dev
          libtree-sitter-dev
          libunibilium-dev
          libuv1-dev
          libvterm-dev
          lua-busted
          lua-check
          lua-filesystem
          lua-inspect
          lua-lpeg
          lua-luv-dev
          lua-nvim
          luajit
      shell: bash

    - if: runner.os == 'macOS'
      run: |
        brew update --quiet
        brew install $DEPENDENCIES ${{ inputs.additional_packages }}
      env:
        DEPENDENCIES: |
          automake
          ninja
      shell: bash
