name: Feature request
description: Request an enhancement for Nvim
type: 'enhancement'
body:

  - type: markdown
    attributes:
      value: |
        Before requesting: search [existing feature requests](https://github.com/neovim/neovim/labels/enhancement) and check the [FAQ](https://neovim.io/doc/user/faq.html).

  - type: textarea
    attributes:
      label: "Problem"
      description: "Describe the problem to be solved. Include references to other projects (Vim, Emacs, etc.) if relevant."
      placeholder: "No smurf icons available. Smurfs are useful because ..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "Describe what the new feature or behavior would look like. How does it solve the problem? Is it worth the cost?"
    validations:
      required: true
