local vars = require 'elisp.vars'

require 'elisp.lread'.init_once()
vars.commit_qsymbols()
require 'elisp.eval'.init_once()

vars.commit_qsymbols()

require 'elisp.charset'.init_syms()
require 'elisp.emacs'.init_syms()
require 'elisp.fns'.init_syms()
require 'elisp.lread'.init_syms()
require 'elisp.data'.init_syms()
require 'elisp.eval'.init_syms()
require 'elisp.editfns'.init_syms()
require 'elisp.buffer'.init_syms()
require 'elisp.alloc'.init_syms()
require 'elisp.dev'.init_syms()
require 'elisp.doc'.init_syms()
require 'elisp.keymap'.init_syms()
require 'elisp.chartab'.init_syms()
require 'elisp.print'.init_syms()
require 'elisp.search'.init_syms()
require 'elisp.fileio'.init_syms()
require 'elisp.timefns'.init_syms()
require 'elisp.callint'.init_syms()
require 'elisp.casetab'.init_syms()
require 'elisp.chars'.init_syms()
require 'elisp.bytecode'.init_syms()
require 'elisp.casefiddle'.init_syms()
require 'elisp.coding'.init_syms()
require 'elisp.textprop'.init_syms()
require 'elisp.xfaces'.init_syms()
require 'elisp.frame'.init_syms()
require 'elisp.font'.init_syms()
require 'elisp.minibuf'.init_syms()
require 'elisp.callproc'.init_syms()
require 'elisp.macros'.init_syms()
require 'elisp.syntax'.init_syms()
require 'elisp.category'.init_syms()
require 'elisp.composite'.init_syms()
require 'elisp.xdisp'.init_syms()
require 'elisp.dispnew'.init_syms()
require 'elisp.ccl'.init_syms()
require 'elisp.terminal'.init_syms()
require 'elisp.floatfns'.init_syms()

vars.commit_qsymbols()

require 'elisp.eval'.init()
require 'elisp.category'.init() --Needs to be loaded before buffer
require 'elisp.syntax'.init() --Needs to be loaded before buffer
require 'elisp.buffer'.init()
require 'elisp.fns'.init()
require 'elisp.lread'.init()
require 'elisp.keymap'.init()
require 'elisp.emacs'.init()
require 'elisp.data'.init()
require 'elisp.casetab'.init()
require 'elisp.charset'.init()
require 'elisp.coding'.init()
require 'elisp.xfaces'.init()
require 'elisp.font'.init()
require 'elisp.minibuf'.init()
require 'elisp.frame'.init()
require 'elisp.chars'.init()
require 'elisp.composite'.init()
require 'elisp.xdisp'.init()
require 'elisp.ccl'.init()
require 'elisp.dispnew'.init()
require 'elisp.textprop'.init()

local name, val = debug.getupvalue(getmetatable(vars.V).__newindex, 1)
assert(name == 'Vsymbols', name)
for k, _ in pairs(val) do
  _ = vars.V[k]
end
