tabpage_T * find_tab(Tabpage tabpage, Error *err);
win_T * find_window(Window window, Error *err);
buf_T *find_buffer(Buffer buffer, Error *err);
Object vim_to_object(typval_T *obj);
void set_option_to(void *to, int type, String name, Object value, Error *err);
Object get_option_from(void *from, int type, String name, Error *err);
Object dict_set_value(dict_T *dict, String key, Object value, Error *err);
Object dict_get_value(dict_T *dict, String key, Error *err);
bool try_end(Error *err);
void try_start(void);
tabpage_T * find_tab(Tabpage tabpage, Error *err);
win_T * find_window(Window window, Error *err);
buf_T *find_buffer(Buffer buffer, Error *err);
Object vim_to_object(typval_T *obj);
void set_option_to(void *to, int type, String name, Object value, Error *err);
Object get_option_from(void *from, int type, String name, Error *err);
Object dict_set_value(dict_T *dict, String key, Object value, Error *err);
Object dict_get_value(dict_T *dict, String key, Error *err);
bool try_end(Error *err);
void try_start(void);
