Boolean tabpage_is_valid(Tabpage tabpage);
Window tabpage_get_window(Tabpage tabpage, Error *err);
Object tabpage_set_var(Tabpage tabpage, String name, Object value, Error *err);
Object tabpage_get_var(Tabpage tabpage, String name, Error *err);
Integer tabpage_get_window_count(Tabpage tabpage, Error *err);
Boolean tabpage_is_valid(Tabpage tabpage);
Window tabpage_get_window(Tabpage tabpage, Error *err);
Object tabpage_set_var(Tabpage tabpage, String name, Object value, Error *err);
Object tabpage_get_var(Tabpage tabpage, String name, Error *err);
Integer tabpage_get_window_count(Tabpage tabpage, Error *err);
