void vim_set_current_tabpage(Tabpage tabpage, Error *err);
Tabpage vim_get_current_tabpage(void);
Integer vim_get_tabpage_count(void);
void vim_set_current_window(Window window, Error *err);
Window vim_get_current_window(void);
Integer vim_get_window_count(void);
void vim_set_current_buffer(Buffer buffer, Error *err);
Buffer vim_get_current_buffer(void);
Integer vim_get_buffer_count(void);
void vim_err_write(String str);
void vim_out_write(String str);
void vim_set_option(String name, Object value, Error *err);
Object vim_get_option(String name, Error *err);
Object vim_get_vvar(String name, Error *err);
Object vim_set_var(String name, Object value, Error *err);
Object vim_get_var(String name, Error *err);
void vim_set_current_line(String line, Error *err);
void vim_del_current_line(Error *err);
String vim_get_current_line(Error *err);
void vim_change_directory(String dir, Error *err);
StringArray vim_list_runtime_paths(void);
Integer vim_strwidth(String str, Error *err);
Object vim_eval(String str, Error *err);
void vim_command(String str, Error *err);
void vim_push_keys(String str);
void vim_set_current_tabpage(Tabpage tabpage, Error *err);
Tabpage vim_get_current_tabpage(void);
Integer vim_get_tabpage_count(void);
void vim_set_current_window(Window window, Error *err);
Window vim_get_current_window(void);
Integer vim_get_window_count(void);
void vim_set_current_buffer(Buffer buffer, Error *err);
Buffer vim_get_current_buffer(void);
Integer vim_get_buffer_count(void);
void vim_err_write(String str);
void vim_out_write(String str);
void vim_set_option(String name, Object value, Error *err);
Object vim_get_option(String name, Error *err);
Object vim_get_vvar(String name, Error *err);
Object vim_set_var(String name, Object value, Error *err);
Object vim_get_var(String name, Error *err);
void vim_set_current_line(String line, Error *err);
void vim_del_current_line(Error *err);
String vim_get_current_line(Error *err);
void vim_change_directory(String dir, Error *err);
StringArray vim_list_runtime_paths(void);
Integer vim_strwidth(String str, Error *err);
Object vim_eval(String str, Error *err);
void vim_command(String str, Error *err);
void vim_push_keys(String str);
