Boolean window_is_valid(Window window);
Tabpage window_get_tabpage(Window window, Error *err);
Position window_get_position(Window window, Error *err);
void window_set_option(Window window, String name, Object value, Error *err);
Object window_get_option(Window window, String name, Error *err);
Object window_set_var(Window window, String name, Object value, Error *err);
Object window_get_var(Window window, String name, Error *err);
void window_set_width(Window window, Integer width, Error *err);
Integer window_get_width(Window window, Error *err);
void window_set_height(Window window, Integer height, Error *err);
Integer window_get_height(Window window, Error *err);
void window_set_cursor(Window window, Position pos, Error *err);
Position window_get_cursor(Window window, Error *err);
Buffer window_get_buffer(Window window, Error *err);
Boolean window_is_valid(Window window);
Tabpage window_get_tabpage(Window window, Error *err);
Position window_get_position(Window window, Error *err);
void window_set_option(Window window, String name, Object value, Error *err);
Object window_get_option(Window window, String name, Error *err);
Object window_set_var(Window window, String name, Object value, Error *err);
Object window_get_var(Window window, String name, Error *err);
void window_set_width(Window window, Integer width, Error *err);
Integer window_get_width(Window window, Error *err);
void window_set_height(Window window, Integer height, Error *err);
Integer window_get_height(Window window, Error *err);
void window_set_cursor(Window window, Position pos, Error *err);
Position window_get_cursor(Window window, Error *err);
Buffer window_get_buffer(Window window, Error *err);
