.TH EVIM 1 "16 Þubat 2002"
.SH AD
evim \- kolay Vim, bir dosyayý Vim ile herhangi bir kip olmadan düzenleyin
.SH ÖZET
.br
.B evim
[seçenekler] [dosya ..]
.br
.B eview
.SH TANIM
.B eVim,
.B Vim'i
baþlatýr ve onu herhangi bir kipsiz düzenleyici gibi davranmasýný saðlar.
Bu bildiðiniz Vim'dir, ancak bir týkla ve yaz düzenleyicisi gibi çalýþýr.
Bir örnek vermek gerekirse MS-Windows üzerindeki Not Defteri gibi düþünün.
.B eVim
menülere ve araç çubuklarýna eriþim saðlayabilmeniz için grafik arabirimde çalýþýr.
.PP
Yalnýzca Vim ile normal biçimde çalýþamayan kiþilerin kullanýmý içindir.
Dosya düzenleme iþi çok daha verimsiz olacaktýr.
.PP
.B eview'ün
aynýsýdýr, ancak saltokunur kipte baþlar. evim \-R ile de baþlatýlabilir.
.PP
Vim hakkýnda ayrýntýlý bilgi için: vim(1)
.PP
Doðrudan metin giriþini saðlayabilmek için 'insertmode' seçeneði açýlýr.
.br
Eþlemlemeler Kopyala ve Yapýþtýr MS-Windows ile ayný olacak biçimde ayarlanýr.
CTRL-X metni keser, CTRL-C metni kopyalar ve CTRL-V metni yapýþtýrýr.
CTRL-V'nin orijinal iþlevi için CTRL-Q kullanýn.
.SH SEÇENEKLER
Bilgi için: vim(1).
.SH DOSYALAR
.TP 15
/usr/local/lib/vim/evim.vim
eVim'i ilklendirmek için kullanýlan betik.
.SH NAM-I DÝÐER
Nam-ý diðer "Lastik Çizmeliler için Vim" (Gumbies, Monty Python).
eVim'i kullanýrken bir mendili alýp iki ucundan birer düðüm yapmanýz
ve kafanýza takmanýz beklenir.
.SH AYRICA BAKINIZ
vim(1)
.SH YAZAR
.B Vim'in
büyük çoðunluðu Bram Moolenaar tarafýndan baþkalarýnýn kayda deðer
yardýmlarýyla yazýlmýþtýr.
Ek bilgi için Yardým/Teþekkürler menüsüne bakýn.
