.TH EVIM 1 "2002 Lut 16"
.SH NAZWA
evim \- ³atwy Vim, edytuj plik w Vimie z ustawieniami dla edycji bez
trybów
.SH SYNOPSIS
.br
.B evim
[opcje] [plik ...]
.br
.B eview
.SH OPIS
.B eVim
uruchamia
.B Vima
i ustawia opcje tak by zachowywa³ siê jak edytor bez trybów.
To jest ca³y czas Vim ale u¿ywany jako edytor wska¿-i-kliknij.
Zachowanie w stylu Notepada dla MS-Windows.
.B eVim
bêdzie zawsze uruchomiony w GUI by w³±czyæ menu i pasek narzêdzi.
.PP
Przeznaczony tylko dla ludzi, którzy naprawdê nie mog± pracowaæ
z Vimem w normalny sposób. Edycja bêdzie o wiele mniej efektywna.
.PP
.B eview
dzia³a tak samo, ale zaczyna w trybie tylko do odczytu. Dzia³a tak
samo jak evim \-R.
.PP
Zobacz vim(1) by poznaæ wiêcej szczegó³ów o Vimie, opcjach, itd.
.PP
Opcja 'insertmode' jest ustawiona by mo¿na by³o od razu wpisywaæ
tekst.
.br
Mapowania s± ustawione tak by Kopiowanie i Wklejanie dzia³a³o
z klawiszami MS-Windows. CTRL-X wycina, CTRL-C kopiuje a CTRL-V 
wkleja tekst. U¿yj CTRL-Q by uzyskaæ oryginalne przeznaczenie
CTRL-V.
.SH OPCJE
Zobacz vim(1).
.SH PLIKI
.TP 15
/usr/local/lib/vim/evim.vim
Skrypt uruchamiania dla eVima.
.SH ZNANY JAKO
Znany jako "Vim dla frajerów".
Je¶li u¿ywasz eVima oczekuje siê, ¿e wyjmiesz chusteczkê do nosa,
zrobisz wêzê³ w ka¿dym rogu i bêdziesz to nosi³ na g³owie.
.SH ZOBACZ TAK¯E
vim(1)
.SH AUTOR
Wiêkszo¶æ 
.B Vima
zosta³a napisana przez Brama Moolenaara z du¿± pomoc± innych osób.
Zobacz menu Help/Credits.
