.TH VIM 1 "2006 kwi 11"
.SH NAME
vim \- Vi rozbudowany, edytor tekstu dla programisty
.SH SYNOPSIS
.br
.B vim
[opcje] [plik ..]
.br
.B vim
[opcje] \-
.br
.B vim
[opcje] \-t znacznik
.br
.B vim
[opcje] \-q [plik_b³êdu]
.PP
.br
.B ex
.br
.B view
.br
.B gvim
.B gview
.B evim
.B eview
.br
.B rvim
.B rview
.B rgvim
.B rgview
.SH OPIS
.B Vim
jest edytorem tekstu kompatybilnym z Vi. Mo¿e byæ
u¿ywany do edycji wszelkiego rodzaju plików tekstowych.
U¿yteczny zw³aszcza przy edycji programów.
.PP
Posiada wiele usprawnieñ w porównaniu z Vi: wielopoziomowe cofanie zmian,
wiele okien i buforów, pod¶wietlanie sk³adni, edycja linii poleceñ,
uzupe³nianie nazw plików, pomoc on-line, wizualna selekcja, itd.
Zobacz ":help vi_diff.txt" dla podsumowania ró¿nic pomiêdzy
.B Vimem
i Vi.
.PP
W czasie korzystania z
.B Vima
mo¿na uzyskaæ obszern± pomoc z systemu pomocy on-line dziêki poleceniu ":help".
Zobacz rozdzia³ POMOC ON-LINE poni¿ej.
.PP
Najczê¶ciej
.B Vim
jest uruchamiany do edycji pojedynczego pliku poleceniem
.PP
	vim plik
.PP
Bardziej ogólnie
.B Vim
jest uruchamiany poprzez:
.PP
	vim [opcje] [lista plików]
.PP
Je¶li brak listy plików edytor rozpocznie z pustym buforem. W innym
wypadku istnieje dok³adnie jedna z czterech mo¿liwo¶ci by wybraæ jeden
lub wiêcej plików do edycji.
.TP 12
plik ..
Lista nazw plików.
Pierwsza nazwa bêdzie nazw± bie¿±cego pliku, który zostanie wczytany
do bufora. Kursor zostanie umieszczony w pierwszym wierszu. Do
kolejnych plików mo¿na przej¶æ dziêki poleceniu ":next". By otworzyæ
plik, którego nazwa zaczyna siê od my¶lnika nale¿y listê plików
poprzedziæ "\-\-".
.TP
\-
Plik do edycji jest wczytany ze standardowego wej¶cia. Polecenia s±
odczytywane ze standardowego wyj¶cia b³êdów, którym powinien byæ
terminal (tty).
.TP
\-t {znacznik}
Plik do edycji i pocz±tkowa pozycja kursora zale¿y od "znacznika",
rodzaju etykiety goto.
{znacznika} szuka siê w pliku tags, zwi±zany z nim plik staje siê
plikiem bie¿±cym i wykonuje siê powi±zane polecenie.
Zazwyczaj u¿ywa siê tego sposobu dla programów w C, w których wypadku
{znacznik} mo¿e byæ nazw± funkcji.
W efekcie plik zawieraj±cy okre¶lon± funkcjê staje siê plikiem
bie¿±cym a kursor jest umieszczony na pocz±tku funkcji.
Zobacz ":help tag-commands".
.TP
\-q [plik_b³êdów]
Zacznij w trybie quickFix.
Plik [plik_b³êdów] zostaje zinterpretowany i poka¿e siê pierwszy b³±d.
Je¶li brak opcji [plik_b³êdów] nazwa pliku zostanie pobrana z opcji
\&'errorfile' (domy¶lnie "AztecC.Err" dla Amigi, "errros.err" dla innych
systemów.
Do kolejnych b³êdów mo¿na przeskoczyæ dziêki poleceniu ":cn".
Zobacz ":help quickfix".
.PP
W zale¿no¶ci od wywo³ania
.B Vim
zachowuje siê inaczej (program mo¿e byæ ca³y czas tym samym
plikiem).
.TP 10
vim
"Normalny" sposób, wszystko jest domy¶lne.
.TP
ex
Zacznij w trybie Ex.
Przejd¼ do trybu Normalnego poleceniem ":vi".
Mo¿na tak¿e uruchomiæ poprzez argument "\-e".
.TP
view
Zacznij w trybie tylko do odczytu. W ten sposób bêdziesz chroniony
przed zapisywaniem pliku. Mo¿na tak¿e uruchomiæ poprzez argument
"\-R".
.TP
gvim gview
Wersja GUI.
Uruchamia nowe okno.
Mo¿na tak¿e uruchomiæ poprzez argument "\-g".
.TP
evim eview
Wersja GUI w ³atwym trybie.
Uruchamia nowe okno.
Mo¿na tak¿e uruchomiæ poprzez argument "\-y".
.TP
rvim rview rgvim rgview
Podobnie jak powy¿ej, ale z ograniczeniami. Nie bêdzie mo¿na uruchomiæ
poleceñ pow³oki lub zawiesiæ
.B Vima.
Mo¿na tak¿e uruchomiæ poprzez argument "\-Z".
.SH OPCJE
Opcje mo¿na podaæ w dowolnej kolejno¶ci, przed lub po nazwach plików.
Opcje bez argumentów mo¿na ³±czyæ po pojedynczym my¶lniku.
.TP 12
+[num]
W pierwszym pliku kursor zostanie umieszczony w wierszu "num".
Je¶li brak "num" kursor zostanie umieszczony w ostatnim wierszu.
.TP
+/{wzór}
W pierwszym pliku kursor zostanie umieszczony na pierwszym wyst±pieniu
{wzór}.
Zobacz ":help search-pattern" by dowiedzieæ siê jakie s± mo¿liwe
wzorce wyszukiwania.
.TP
+{polecenie}
.TP
\-c {polecenie}
{polecenie} zostanie wykonane po tym jak wczyta siê pierwszy plik.
{polecenie} jest interpretowane jako polecenie Ex.
Je¶li {poleceni} zawiera bia³e znaki musi byæ umieszczone w podwójnych
cudzys³owach (zale¿y to od u¿ywanej pow³oki).
Przyk³ad: Vim "+set si" main.c
.br
Uwaga: Mo¿na u¿yæ do 10 poleceñ "+" lub "\-c".
.TP
\-S {plik}
{plik} zostanie zinterpretowany po wczytaniu pierwszego pliku.
Jest równowa¿ne \-c "source {plik}".
{plik} nie mo¿e zaczynaæ siê '\-'.
Je¶li nie podano {plik} zostanie u¿yty "Session.vim" (dzia³a tylko
wtedy je¶li \-S jest ostatnim argumentem).
.TP
\-\-cmd {polecenie}
Podobne do "\-c", ale polecenie jest wykonywane tu¿ przed
interpretacj± jakiegokolwiek pliku vimrc.
Mo¿na u¿yæ do 10 takich poleceñ, niezale¿nie od poleceñ od "\-c"
.TP
\-A
Je¶li
.B Vim
zosta³ skompilowany ze wsparciem dla jêzyków arabskich (edycja od
prawej do lewej i arabska mapa klawiatury) ta opcja uruchamia
.B Vima
w trybie arabskim, np. ustawia siê opcja 'arabic'. W innym wypadku
pojawi siê komunikat b³êdu i
.B Vim
zakoñczy dzia³anie.
.TP
\-b
Tryb binarny.
Ustawi siê kilka opcji, które umo¿liwi± edycjê plików binarnych lub
wykonywalnych.
.TP
\-C
Kompatybilny. Ustawia opcjê 'compatible'.
W ten sposób 
.B Vim
bêdzie zachowywa³ siê jak Vi, nawet je¶li istnieje plik .vimrc.
.TP
\-d
Uruchom w trybie diff.
Powinno siê u¿yæ dwóch, trzech lub czterech nazwy plików jako argumentów.
.B Vim
otworzy wszystkie te pliki i poka¿e ró¿nice miêdzy nimi.
Dzia³a jak vimdiff(1).
.TP
\-d {urz±dzenie}
Otwórz {urz±dzenie} by u¿ywaæ jako terminal.
Tylko na Amidze.
Przyk³ad:
"\-d con:20/30/600/150".
.TP
\-D
Debugowanie. Przejd¼ do trybu debugowanie wykonuj±c pierwsze polecenie
ze skryptu.
.TP
\-e
Uruchom
.B Vima
w trybie Ex, dzia³a tak samo jakby wywo³ano program jako "ex".
.TP
\-E
Uruchom
.B Vima
w ulepszonym trybie Ex, dzia³a tak samo jakby wywo³ano program jako
"exim".
.TP
\-f
Pierszy plan. Dla wersji GUI.
.B Vim
nie nie oddzieli siê od pow³oki w jakiej zosta³ uruchomiony. Na Amidze
.B Vim
nie jest uruchomiony ponownie by otworzyæ nowe okno.
Opcja powinna byæ u¿yta kiedy
.B Vim
jest wywo³ywany przez program, który ma zaczekaæ na koniec sesji (np.
mail).
Na Amidze polecenia ":sh" i ":!" nie bêd± dzia³aæ.
.TP
\-\-nofork
Pierwszy plan. Dla wersji GUI.
.B Vim
nie oddzieli siê od pow³oki w jakiej zosta³ uruchomiony.
.TP
\-F
Je¶li Vim zosta³ skompilowany ze wsparciem FKMAP dla edycji tekstów od
prawej do lewej i mapowania klawiatury Farsi, ta opcja uruchomi
.B Vima
w trybie Farsi, np. zostawi± ustawione opcje 'fkmap' i 'rightleft'.
W innym wypadku pojawi siê komunikat b³êdu i
.B Vim
zakoñczy dzia³anie.
.TP
\-g
Je¶li
.B Vim
zosta³ skompilowany ze wsparciem dla GUI ta opcja uruchomi GUI.
W innym wypadku pojawi siê komunikat b³êdu i
.B Vim
zakoñczy dzia³anie.
.TP
\-h
Wy¶wietli krótk± pomoc o argumentach linii poleceñ i opcjach. Potem
.B Vim
zakoñczy dzia³anie.
.TP
\-H
Je¶li
.B Vim
zosta³ skompilowany ze wsparciem RIGHTLEFT dla edycji od prawej do
lewej oraz ma mapowanie klawiatury dla hebrajskiego, ta opcja uruchomi
.B Vima
w trybie hebrajskim, np. ustawi opcje 'hkmap' i 'rightleft'.
W innym wypadku pojawi siê komunikat b³êdu i
.B Vim
zakoñczy dzia³anie.
.TP
\-i {viminfo}
Kiedy
.B Vim
u¿ywa pliku viminfo ta opcja wska¿e jakiego pliku u¿yæ zamiast
domy¶lnego "~/.viminfo".
Mo¿na te¿ omin±æ u¿ycie pliku .viminfo przez podanie nazwy "NONE".
.TP
\-L
To samo co \-r.
.TP
\-l
Tryb Lisp.
Ustawia opcje 'lisp' i 'showmatch'.
.TP
\-m
Zmiana pliku jest niemo¿liwa.
Przestawia opcjê 'write'.
Mo¿na zmieniaæ zawarto¶æ bufora, ale zapisanie pliku nie jest
mo¿liwe.
.TP
\-M
Opcje 'modifiable' i 'write' zostan± wy³±czone, tak wiêc zmiany
w pliku oraz ich zapisanie nie s± mo¿liwe. Warto¶æ tych opcji mo¿na
zmieniæ.
.TP
\-N
Tryb niekompatybilny. Przestawia opcjê 'compatible'. Dziêki temu
.B Vim
bêdzie zachowywa³ siê odrobinê lepiej, ale mniej zgodnie z Vi nawet
je¶li nie istnieje plik .vimrc.
.TP
\-n
Nie powstanie plik wymiany. Odzyskanie pliku po wypadku nie bêdzie
mo¿liwe.
Wygodne je¶li instnieje potrzeba edycji na bardzo wolnym medium (np.
dyskietce). Ten cel mo¿na osi±gn±æ tak¿e przez ":set uc=0". Mo¿na
odwróciæ przez ":set uc=200".
.TP
\-nb
Uruchom jako serwer edytora dla NetBeans. Zobacz dokumentacjê by
dowiedzieæ siê wiêcej.
.TP
\-o[N]
Otwórz N okien w stosie.
Kiedy brak N, otwórz jedno okno dla ka¿dego pliku.
.TP
\-O[N]
Otwórz N okien obok siebie.
Kiedy brak N, otwórz jedno okno dla ka¿dego pliku.
.TP
\-p[N]
Otwórz N kart.
Kiedy brak N, otwórz jedn± kartê dla ka¿dego pliku.
.TP
\-R
Tryb tylko do odczytu.
Zostanie ustawiona opcja 'readonly'.
Ca³y czas mo¿na zmieniaæ bufor, ale bêdzie istnia³a blokada by chroniæ
przed przypadkowym zapisaniem pliku.
Je¶li chcesz zapisaæ plik dodaj wykrzyknik do polecenia Ex, np. ":w!".
Opcja \-R implikuje opcjê \-n (zobacz poni¿ej).
Opcja 'readonly' mo¿e zostaæ przestawiona poprzez ":set noro".
Zobacz ":help 'readonly'".
.TP
\-r
Wypisz listê plików wymiany razem z informacjami o nich.
.TP
\-r {plik}
Tryb odzyskiwania danych.
Plik wymiany zostanie wykorzystany do odzyskania gwa³townie przerwanej sesji.
Plik wymiany to plik z tak± sam± nazw± co plik oryginalny z dodanym ".swp".
Zobacz ":help recovery".
.TP
\-s
Tryb cichy. Rozpoczêty tylko kiedy uruchomiony jako "Ex" lub opcja
"\-e" zosta³a podana przed opcj± "\-s".
.TP
\-s {skrypt}
Zostanie wczytany plik {skrypt}.
Znaki w pliku zostan± zinterpretowane jakby by³y wpisywane.
To samo mo¿na osi±gn±æ poprzez polecenie ":source! {skrypt}".
Je¶li osi±gniêto koniec pliku zanim edytor zakoñczy³ dzia³anie, dalsze
znaki odczytywane s± z klawiatury.
.TP
\-T {terminal}
Przekazuje
.B Vimowi
nazwê terminalu jakiego u¿ywasz.
Wymagane tylko wtedy je¶li nie dzia³a automatycznie.
Powinien byæ to terminal znany
.B Vimowi
(builtin) lub zdefiniowany w plikach termcap lub terminfo.
.TP
\-u {vimrc}
U¿yj poleceñ z pliku {vimrc} w czasie uruchamiania.
Wszystkie inne mo¿liwe pliki uruchamiania zostan± pominiête.
U¿ywaj do edytowania plików specjalnych.
Mo¿na pomin±æ tak¿e wszystkie mo¿liwe pliki uruchamiania poprzez
podanie nazwy "NONE".
Zobacz ":help initialization" by poznaæ wiêcej szczegó³ów.
.TP
\-U {gvimrc}
U¿yj poleceñ z pliku {gvimrc} w czasie uruchamiania GUI.
Wszystkie inne mo¿liwe pliki uruchamiania GUI zostan± pominiête.
Mo¿na pomin±æ tak¿e wszystkie mo¿liwe pliki uruchamiania GUI poprzez
podanie nazwy "NONE".
Zobacz ":help gui-init" by poznaæ wiêcej szczegó³ów.
.TP
\-V[N]
Tryb gadatliwy. Wypisz wiadomo¶ci o tym jaki pliki s± wczytywane
i o informacjach pobieranych i dodawanych do pliku viminfo. Opcjonalny
argument N jest warto¶ci± 'verbose'. Domy¶lnie 10.
.TP
\-v
Uruchom
.B Vima
w trybie Vi, tak jakby program by³ nazwany "vi". Ma znaczenie
tylko wtedy je¶li program nazwany jest "ex".
.TP
\-w {plik}
Wszystkie wci¶niêcia klawiszy, a¿ do zakoñczenia dzia³ania programu,
s± zapisywane w {plik} .
U¿yteczne je¶li chce siê stworzyæ skrypt do u¿ycia z "vim \-s" lub
":source!".
Je¶li {plik} istnieje, znaki s± dopisywane.
.TP
\-W {plik}
Podobnie do \-w, ale istniej±cy plik jest nadpisywany.
.TP
\-x
U¿yj szyfrowania podczas zapisywania plików. Zostaniesz poproszony
o podanie klucza.
.TP
\-X
Nie ³±cz z serwerem X. Skraca czas uruchamiania w terminalu, ale tytu³
okna i schowek nie bêd± wykorzystywane.
.TP
\-y
Uruchom
.B Vima
w ³atwym trybie, tak jakby program zosta³ wywo³any "evim" lub "eview".
.B Vim
bêdzie zachowywa³ siê bardziej jak edytor kliknij-i-wpisz.
.TP
\-Z
Tryb ograniczony. Zachowuje siê jakby nazwa programu zaczyna³a siê od
"r".
.TP
\-\-
Oznacza koniec opcji.
Argumenty po tej opcji bêd± traktowane jak nazwy plików. U¿ywa siê do
otwierania plików, których nazwy zaczynaj± siê od '\-'.
.TP
\-\-echo\-wid
Wy³±cznie GTK GUI: wypisz ID okna na standardowe wyj¶cie.
.TP
\-\-help
Wy¶wietl informacjê o pomocy i zakoñczy, to samo co"\-h".
.TP
\-\-literal
Potraktuj nazwy plików dos³ownie i nie rozwi±zuj kwantyfikatorów. Nie
ma znaczenia na Uniksach gdzie pow³oka rozwi±zuje kwantyfikatory.
.TP
\-\-noplugin
Pomiñ ³adowanie wtyczek. Implikowane przy \-u NONE.
.TP
\-\-remote
Po³±cz siê z serwerem Vima i edytuj w nim resztê plików podanych jako
argumenty. Je¶li nie znaleziono serwera zostanie zg³oszony b³±d a pliki zostan±
otwarte w bie¿±cym Vimie.
.TP
\-\-remote\-expr {wyra¿enie}
Po³±cz z serwerem Vima, rozwi±¿ w nim {wyra¿enie} i wypisz rozwi±zanie
na standardowe wyj¶cie.
.TP
\-\-remote\-send {klawisze}
Po³±cz z serwerem Vima i wy¶lij do niego {klawisze}.
.TP
\-\-remote\-silent
Tak samo jak \-remote, ale bez ostrze¿enia kiedy nie znaleziono
serwera.
.TP
\-\-remote\-wait
Tak samo jak \-remote, ale Vim nie zakoñczy dopóki pliki pozostan±
otwarte.
.TP
\-\-remote\-wait\-silent
Tak samo jak \-\-remote\-wait, ale bez ostrze¿enie kiedy nie
znaleziono serwera.
.TP
\-\-serverlist
Wypisz nazwy wszystkich serwerów Vima jakie mo¿na znale¼æ.
.TP
\-\-servername {nazwa}
U¿yj {nazwa} jako nazwy serwera. Wykorzystane dla bie¿±cego Vima o ile
nie po³±czone z argumentem \-\-remote, wtedy jest to nazwa serwera do
po³±czenia.
.TP
\-\-socketid {id}
Wy³±cznie GTK GUI: U¿yj mechanizmu GtkPlug by uruchomiæ gvima w innym
oknie.
.TP
\-\-version
Wypisz informacjê o wersji i zakoñcz.
.SH POMOC ON-LINE
By rozpocz±æ wpisz ":help" w
.B Vimie
Wpisz ":help temat" by uzyskaæ pomoc na okre¶lony temat.
Przyk³ad: ":help ZZ" by uzyskaæ pomoc na temat polecenia "ZZ".
U¿yj <Tab> i CTRL\-D aby uzupe³niæ tematy (":help
cmdline\-completion"). W plikach pomocy istniej± znaczniki by u³atwiæ
skakanie z jednego miejsca do innego (rodzaj linków hipertekstowych,
zobacz ":help").
Mo¿na w ten sposób zobaczyæ ca³± dokumentacjê, np. ":help syntax.txt".
.SH PLIKI
.TP 15
/usr/local/lib/vim/doc/*.txt
Dokumentacja
.B Vima
U¿yj ":help doc\-file\-list" aby uzyskaæ pe³n± listê.
.TP
/usr/local/lib/vim/doc/tags
Plik znaczników s³u¿y do znajdowania informacji w plikach dokumentacji.
.TP
/usr/local/lib/vim/syntax/syntax.vim
Globalne uruchamianie pod¶wietlania sk³adni.
.TP
/usr/local/lib/vim/syntax/*.vim
Pliki sk³adni dla ró¿nych jêzyków.
.TP
/usr/local/lib/vim/vimrc
Globalny plik uruchamiania
.B Vima
.TP
~/.vimrc
Osobiste parametry uruchamiania
.B Vima
.TP
/usr/local/lib/vim/gvimrc
Globalne uruchamianie gvima.
.TP
~/.gvimrc
Osobiste parametry uruchamiania gvima.
.TP
/usr/local/lib/vim/optwin.vim
Skrypt u¿ywany w poleceniu ":options", dobry sposób do przegl±dania
i ustawiania opcji.
.TP
/usr/local/lib/vim/menu.vim
Globalne uruchamianie menu gvima.
.TP
/usr/local/lib/vim/bugreport.vim
Skrypt s³u¿±cy do tworzenia raportów o b³êdach. Zobacz ":help bugs".
.TP
/usr/local/lib/vim/filetype.vim
Skrypt do wykrywania typu pliku wed³ug jego nazwy. Zobacz ":help 'filetype'".
.TP
/usr/local/lib/vim/scripts.vim
Skrypt do wykrywania typu pliku wed³ug jego zawarto¶ci. Zobacz ":help 'filetype'".
.TP
/usr/local/lib/vim/print/*.ps
Pliku u¿ywane do drukowania PostScriptu.
.PP
Naj¶wie¿sze wiadomo¶ci na stronie
.B Vima:
.br
<URL:http://www.vim.org/>
.SH ZOBACZ TAK¯E
vimtutor(1)
.SH AUTOR
.B Vim
zosta³ napisany przez Brama Moolenaara z du¿± pomoc± innych osób.
Zobacz ":help credits" w
.B Vimie.
.br
.B Vim
bazuje na Steviem, nad którym pracowali: Tim Thompson, Tony Andrews
i G.R. (Fred) Walter.
Ma³o ju¿ zosta³o z oryginalnego kodu.
.SH B£ÊDY
Prawdopodobne.
Zobacz ":help todo" by poznaæ listê znanych problemów.
.PP
Pamiêtaj ¿e pewna ilo¶æ problemów, które mog± byæ uznawane przez
niektórych ludzi za b³êdy s± w rzeczywisto¶ci spowodowane wierno¶ci±
w odtwarzaniu zachowania Vi.
Je¶li s±dzisz, ¿e inne rzeczy s± b³êdami "poniewa¿ Vi robi to
inaczej", powiniene¶ przyjrzeæ siê bli¿ej plikowi vi_diff.txt (lub
wpisaæ ":help vi_diff.txt" w Vimie).
Sprawd¼ tak¿e opis opcji 'compatible' i 'cpoptions'.
