.TH VIMTUTOR 1 "2 Nisan 2001"
.SH AD
vimtutor \- Vim eðitmeni
.SH ÖZET
.br
.B vimtutor [\-g] [dil]
.SH TANIM
.B Vimtutor,
.B Vim
eðitmenini baþlatýr.
Önce orijinal eðitmen dosyasýnýn bir kopyasýný alýr, böylece bir deðiþikliðe
uðramadan deðiþtirilebilir.
.PP
.B Vimtutor
ilk
.B Vim
komutlarýný öðrenmek isteyen kiþiler için yararlýdýr.
.PP
Ýsteðe baðlý \-g deðiþkeni vimtutor'u vim yerine eðer yüklü ise gvim ile
baþlatýr. Yüklü deðilse açmak için Vim kullanýlýr.
.PP
Ýsteðe baðlý [dil] deðiþkeni iki harfli dil kodunu belirtir, örneðin "tr"
veya "es". Eðer [dil] deðiþkeni verilmemiþse mevcut yerelleþtirme
kullanýlýr.
Eðer bu dilde bir eðitmen varsa kullanýlýr.
Yoksa Ýngilizce sürüm kullanýlacaktýr.
.PP
.B Vim
her zaman Vi uyumlu kipte baþlatýlýr.
.SH DOSYALAR
.TP 15
/usr/local/lib/vim/tutor/tutor[.dil]
.B Vimtutor
metin dosyalarý.
.TP 15
/usr/local/lib/vim/tutor/tutor.vim
.B Vimtutor
metin dosyasýný kopyalamak için kullanýlan betik.
.SH YAZAR
.B Vimtutor
ilk olarak Vi için Michael C. Pierce ve Robert K. Ware, 
Colorado School of Mines tarafýndan, Colorado State University'den Charles
Smith'in verdiði fikirler kullanýlarak yazýldý.
E-posta: bware@mines.colorado.edu.
.br
.B Vim
uyarlamasý Bram Moolenaar tarafýndan yapýldý.
Çevirmenlerin adlarý için eðitmen dosyalarýna bakýn.
.SH AYRICA BAKINIz
vim(1)
