.TH VIMTUTOR 1 "2001 April 2"
.SH ИМЯ
vimtutor \- учебник по Vim
.SH КОМАНДНАЯ СТРОКА
.br
.B vimtutor [язык]
.SH ОПИСАНИЕ
Команда
.B vimtutor
запускает учебник по
.B Vim.
При этом сначала происходит создание копии файла учебника, 
чтобы его можно было редактировать без опасения потерять исходный файл.
.PP
Программа
.B vimtutor
полезна для новичков, желающих научиться самым основным командам
.B Vim.
.PP
Необязательный параметр [язык] представляет собой двухсимвольный код языка,
например "ru" или "it".
Если параметр [язык] не указан, то используется язык активной в настоящий 
момент локали. Если учебник на этом языке не существует, то по умолчанию 
используется учебник на английском языке.
.PP
При работе с учебником
.B Vim
всегда запускается в режиме совместимости с Vi.
.SH ФАЙЛЫ
.TP 15
/usr/local/lib/vim/tutor/tutor[.язык]
Текст учебника
.B vimtutor.
.TP 15
/usr/local/lib/vim/tutor/tutor.vim
Сценарий Vim, который используется для создания рабочей
копии текста учебника
.B vimtutor.
.SH АВТОРЫ
.B Vimtutor
был впервые написан для Vi Майклом К. Пирсом (Michael C. Pierce) и
Робертом К. Уэа (Robert K. Ware) из Colorado School of Mines по
идее Чарльза Смита (Charles Smith) из Colorado State University.
E-mail: bware@mines.colorado.edu.
.br
Впоследствии учебник был доработан для использования в 
.B Vim
Брамом Мооленааром (Bram Moolenaar).
Имена переводчиков учебника упоминаются в соответствующих файлах.
.SH СМОТРИ ТАКЖЕ
vim(1)
