.TH VIMTUTOR 1 "2001 Kwi 2"
.SH NAZWA
vimtutor \- nauczyciel Vima
.SH SYNOPSIS
.br
.B vimtutor -g [jêzyk]
.SH OPIS
.B Vimtutor
uruchamia nauczyciela
.B Vima.
Najpierw kopiuje w³a¶ciwy plik, dziêki temu mo¿na go zmieniaæ bez obaw
utraty tre¶ci.
.PP
.B Vimtutor
przyda siê ludziom, którzy chc± siê nauczyæ pierwszych poleceñ
.B Vima
.PP
Opcjonalny argument \-g uruchamia vimtutor w gvimie a nie w Vimie je¶li
graficzna wersja Vima jest dostêpna, je¶li nie zostanie uruchomiony Vim.
.PP
Opcjonalny argument [jêzyk] jest dwu literowym kodem jêzyka, tak jak
"it" lub "es".
Je¶li brak argumentu [jêzyk] zostanie u¿yty jêzyk bie¿±cej
lokalizacji.
Je¶li nauczyciel w tym jêzyku jest dostêpny, zostanie u¿yty \- w innym
wypadku zostanie wykorzystana wersja angielska.
.PP
.B Vim
jest uruchamiany zawsze w trybie kompatybilno¶ci z Vi
.SH PLIKI
.TP 15
/usr/local/lib/vim/tutor/tutor[.jêzyk]
Tekstowe pliki
.B Vimtutora.
.TP 15
/usr/local/lib/vim/tutor/tutor.vim
Skrypt Vima u¿ywany do kopiowania pliku
.B Vimtutora.
.SH AUTOR
.B Vimtutor
zosta³ pocz±tkowo napisany dla Vi przez Michaela C. Pierce'a
i Roberta K. Ware'a z Colorado School of Mines zainspirowani przez
Charlesa Smitha z Colorado State University.
E-mail: bware@mines.colorado.edu
.br
Zmodyfikowany na potrzeby
.B Vima
przez Brama Moolenaara.
Nazwiska t³umaczy w plikach.
.SH ZOBACZ TAK¯E
vim(1)
