.TH VIMDIFF 1 "2001 March 30"
.SH ИМЯ
vimdiff \- позволяет редактировать две или три версии файла с помощью Vim 
с отображением различий.
.SH КОМАНДНАЯ СТРОКА
.br
.B vimdiff
[ключи] файл1 файл2 [файл3]
.PP
.B gvimdiff
.SH ОПИСАНИЕ
Команда
.B vimdiff
загружает в
.B Vim
два (или три) файла. Каждый файл открывается в собственном окне.
Различия между файлами отображаются с помощью подсветки синтаксиса.
Эта команда позволяет наглядно отображать внесённые изменения и переносить
различающиеся фрагменты из одной версии файла в другую.
.PP
Подробнее о Vim см. на странице справочника vim(1).
.PP
При запуске с помощью команды
.B gvimdiff 
редактор запускается в режиме графического интерфейса, если это возможно.
.PP
В каждом окне включается опция 'diff', что позволяет использовать подсветку 
синтаксиса для отображения различий между файлами.
.br
Для улучшения работы с файлами в режиме отображения отличий также включаются
опции 'wrap' и 'scrollbind'.
.br
Значение опции 'foldmethod' устанавливается равным "diff", что позволяет
прятать в складку области текста, которые не отличаются в различных версиях файла.
Значение опции 'foldcolumn' устанавливается равным 2, чтобы было проще 
находить, открывать и закрывать такие складки.
.SH КЛЮЧИ ЗАПУСКА
Для выравнивания строк между окнами используется вертикальное разделение окон,
как если бы использовался ключ "\-O". Для того, чтобы использовать разделение
окон по горизонтали, следует указать в командной строке ключ "\-o".
.PP
Остальные ключи командной строки рассматриваются на странице справочника vim(1).
.SH СМОТРИ ТАКЖЕ
vim(1)
.SH АВТОРЫ
Большая часть
.B Vim
создана Брамом Мооленааром (Bram Moolenaar), которому помогает огромное 
количество людей. См. ":help credits" в
.B Vim.
