.TH EVIM 1 "2002 Lut 16"
.SH NAZWA
evim \- łatwy Vim, edytuj plik w Vimie z ustawieniami dla edycji bez
trybów
.SH SYNOPSIS
.br
.B evim
[opcje] [plik ...]
.br
.B eview
.SH OPIS
.B eVim
uruchamia
.B Vima
i ustawia opcje tak by zachowywał się jak edytor bez trybów.
To jest cały czas Vim ale używany jako edytor wskaż-i-kliknij.
Zachowanie w stylu Notepada dla MS-Windows.
.B eVim
będzie zawsze uruchomiony w GUI by włączyć menu i pasek narzędzi.
.PP
Przeznaczony tylko dla ludzi, którzy naprawdę nie mogą pracować
z Vimem w normalny sposób. Edycja będzie o wiele mniej efektywna.
.PP
.B eview
działa tak samo, ale zaczyna w trybie tylko do odczytu. Działa tak
samo jak evim \-R.
.PP
Zobacz vim(1) by poznać więcej szczegółów o Vimie, opcjach, itd.
.PP
Opcja 'insertmode' jest ustawiona by można było od razu wpisywać
tekst.
.br
Mapowania są ustawione tak by Kopiowanie i Wklejanie działało
z klawiszami MS-Windows. CTRL-X wycina, CTRL-C kopiuje a CTRL-V 
wkleja tekst. Użyj CTRL-Q by uzyskać oryginalne przeznaczenie
CTRL-V.
.SH OPCJE
Zobacz vim(1).
.SH PLIKI
.TP 15
/usr/local/lib/vim/evim.vim
Skrypt uruchamiania dla eVima.
.SH ZNANY JAKO
Znany jako "Vim dla frajerów".
Jeśli używasz eVima oczekuje się, że wyjmiesz chusteczkę do nosa,
zrobisz węzęł w każdym rogu i będziesz to nosił na głowie.
.SH ZOBACZ TAKŻE
vim(1)
.SH AUTOR
Większość 
.B Vima
została napisana przez Brama Moolenaara z dużą pomocą innych osób.
Zobacz menu Help/Credits.
