.TH VIMDIFF 1 "2001 March 30"
.SH 名前
vimdiff \- 二つか三つか四つのファイルを Vim で開いて、その差分を表示する
.SH 書式
.br
.B vimdiff
[options] file1 file2 [file3 [file4]]
.PP
.B gvimdiff
.SH 説明
.B Vimdiff
は、二つ (か三つか四つ) のファイルを
.B Vim
で開きます。
ファイルは個別のウィンドウで開かれ、差分が強調表示されます。
同じファイルの別のバージョン間で、変更を確認したり、変更を移動したりするのが
簡単になります。
.PP
Vim についての詳細は vim(1) を参照してください。
.PP
.B gvimdiff
という名前で起動された場合は GUI で起動します。
.PP
差分を強調表示するために、
それぞれのウィンドウの 'diff' オプションがオンに設定されます。
.br
テキストを見やすくするために、オプションの 'wrap' と 'scrollbind' もオンに設
定されます。
.br
 'foldmethod' オプションは "diff" に設定され、変更されていない行は折り畳まれ
ます。
折り畳みの確認と開閉が簡単にできるように、'foldcolumn' は 2 に設定されます。
.SH オプション
行を並べて表示するために、"\-O" 引数を使ったときのように、ウィンドウは垂直分
割されます。
ウィンドウを水平分割したい場合は "\-o" 引数を使ってください。
.PP
その他の引数については vim(1) を参照してください。
.SH 関連項目
vim(1)
.SH 著者
.B Vim
のほとんどの機能は Bram Moolenaar が開発し、多くの人が協力しました。
":help credits" を参照してください。
