.TH VIMTUTOR 1 "2001 April 2"
.SH 名前
vimtutor \- Vim チュートリアル
.SH 書式
.br
.B vimtutor [\-g] [language]
.SH 説明
.B Vim
のチュートリアルを起動します。
演習ファイルのコピーを使って実施するので、オリジナルの演習ファイルを壊してし
まう心配はありません。
.PP
.B Vim
を初めて学ぶ人向けのチュートリアルです。
.PP
引数に \-g を指定すると GUI 版の vim が利用可能であれば vim ではなく gvim を
使って vimtutor が開始します。gvim が見つからないときは Vim が使用されます。
.PP
[language] 引数は "ja" や "es" などの二文字の言語名です。
[language] 引数を省略した場合はロケールの言語が使われます。
翻訳された演習ファイルがある場合は、そのファイルが使われます。
ない場合は英語のファイルが使われます。
.PP
.B Vim
は Vi 互換モードで起動されます。
.SH ファイル
.TP 15
/usr/local/lib/vim/tutor/tutor[.language]
.B Vimtutor
の演習ファイル。
.TP 15
/usr/local/lib/vim/tutor/tutor.vim
演習ファイルをコピーするための Vim スクリプト。
.SH 著者
.B Vimtutor
は、Colorado State University の Charles Smith のアイデアを基に、
Colorado School of Mines の Michael C.  Pierce と Robert K. Ware の両名
によって Vi 向けに作成されたものを基にしています。
E-mail: bware@mines.colorado.edu.
.br
.B Vim
に合わせて Bram Moolenaar が変更を加えました。
翻訳者の名前は演習ファイルを参照してください。
.SH 関連項目
vim(1)
