local t = require('test.testutil')
local n = require('test.functional.testnvim')()

local clear = n.clear
local command = n.command
local feed = n.feed
local eq = t.eq

describe('position-aware cabbrev (:prefix)', function()
  before_each(function()
    clear()
    command('let g:hit = 0')
  end)

  it('expands at command position (CR)', function()
    command('cabbrev :w :let g:hit = 1')
    feed(':w<CR>')
    eq(1, n.eval('g:hit'))
  end)

  it('expands at command position (space trigger)', function()
    command('cabbrev :w :let g:hit = 1')
    feed(':w <CR>')
    eq(1, n.eval('g:hit'))
  end)

  it('single character mapping expands at command position', function()
    command('cabbrev :e :let g:hit = 1')
    feed(':e<CR>')
    eq(1, n.eval('g:hit'))
  end)

  it('single character mapping does not expand in argument position', function()
    command('cabbrev :e :let g:hit = 1')
    feed(':echo e<CR>')
    eq(0, n.eval('g:hit'))
  end)

  it('abbreviated form of LHS still expands', function()
    command('cabbrev :delete :let g:hit = 1')
    feed(':d<CR>')
    eq(1, n.eval('g:hit'))
  end)

  it('does not expand when word is a command argument', function()
    command('cabbrev :w :let g:hit = 1')
    feed(':echo w<CR>')
    eq(0, n.eval('g:hit'))
  end)

  it('does not expand when used as a variable name', function()
    command('cabbrev :w :let g:hit = 1')
    feed(':let g:w = 1<CR>')
    eq(0, n.eval('g:hit'))
  end)

  it('does not expand mid-argument', function()
    command('cabbrev :e :let g:hit = 1')
    feed(':let g:e = 1<CR>')
    eq(0, n.eval('g:hit'))
  end)

  it('unknown command LHS expands via exact match at command position', function()
    command('cabbrev :duckman :let g:hit = 1')
    feed(':duckman<CR>')
    eq(1, n.eval('g:hit'))
  end)

  it('unknown command LHS does not expand in argument position', function()
    command('cabbrev :duckman :let g:hit = 1')
    feed(':echo duckman<CR>')
    eq(0, n.eval('g:hit'))
  end)

  it('expands as command after pipe', function()
    command('cabbrev :w :let g:hit = 1')
    feed(':let g:x = 0 | w<CR>')
    eq(1, n.eval('g:hit'))
  end)

  it('does not expand in argument position after pipe', function()
    command('cabbrev :w :let g:hit = 1')
    feed(':let g:x = 0 | echo w<CR>')
    eq(0, n.eval('g:hit'))
  end)

  it('expands as command after pipe with range', function()
    n.api.nvim_buf_set_lines(0, 0, -1, true, { 'a', 'b', 'c' })
    command('cabbrev :d :delete')
    feed(':let g:x = 0 | 1,2d<CR>')
    eq({ 'c' }, n.api.nvim_buf_get_lines(0, 0, -1, true))
  end)

  it('does not expand argument after pipe with range', function()
    command('cabbrev :w :let g:hit = 1')
    feed(':let g:x = 0 | echo 1,2w<CR>')
    eq(0, n.eval('g:hit'))
  end)

  it('expands after a line range', function()
    n.api.nvim_buf_set_lines(0, 0, -1, true, { 'a', 'b', 'c' })
    command('cabbrev :d :delete')
    feed(':2,3d<CR>')
    eq({ 'a' }, n.api.nvim_buf_get_lines(0, 0, -1, true))
  end)

  it('abclear removes position-aware abbreviation', function()
    command('cabbrev :w :let g:hit = 1')
    command('abclear')
    feed(':w<CR>')
    eq(0, n.eval('g:hit'))
  end)

  it('cabclear removes position-aware abbreviation', function()
    command('cabbrev :w :let g:hit = 1')
    command('cabclear')
    feed(':w<CR>')
    eq(0, n.eval('g:hit'))
  end)

  it('abclear removes regular cabbrev too', function()
    command('cabbrev w :let g:hit = 1')
    command('abclear')
    feed(':w<CR>')
    eq(0, n.eval('g:hit'))
  end)

  it('cabclear does not affect insert abbreviations', function()
    command('iabbrev w :let g:hit = 1')
    command('cabbrev :w :let g:hit = 2')
    command('cabclear')
    feed(':w<CR>')
    eq(0, n.eval('g:hit'))
  end)

  it('regular cabbrev expands at command position', function()
    command('cabbrev w :let g:hit = 1')
    feed(':w<CR>')
    eq(1, n.eval('g:hit'))
  end)

  it('regular cabbrev does not expand in argument position', function()
    command('cabbrev w :let g:hit = 1')
    feed(':echo w<CR>')
    eq(0, n.eval('g:hit'))
  end)

  it('regular cabbrev is cleared by abclear', function()
    command('cabbrev w :let g:hit = 1')
    command('abclear')
    feed(':w<CR>')
    eq(0, n.eval('g:hit'))
  end)

  it('regular abbrev still works after position-aware is cleared', function()
    command('cabbrev :w :let g:hit = 1')
    command('cabbrev w :let g:hit = 2')
    command('cabclear')
    command('let g:hit = 0')
    command('cabbrev w :let g:hit = 2')
    feed(':w<CR>')
    eq(2, n.eval('g:hit'))
  end)

  it('iabbrev is unaffected by cabclear', function()
    command('iabbrev w :let g:hit = 1')
    command('cabclear')
    feed('iw <Esc>')
    eq(0, n.eval('g:hit'))
  end)
end)
