local RANGE = 0x001
local BANG = 0x002
local EXTRA = 0x004
local XFILE = 0x008
local NOSPC = 0x010
local DFLALL = 0x020
local WHOLEFOLD = 0x040
local NEEDARG = 0x080
local TRLBAR = 0x100
local REGSTR = 0x200
local COUNT = 0x400
local NOTRLCOM = 0x800
local ZEROR = 0x1000
local USECTRLV = 0x2000
local NOTADR = 0x4000
local EDITCMD = 0x8000
local BUFNAME = 0x10000
local BUFUNL = 0x20000
local ARGOPT = 0x40000
local SBOXOK = 0x80000
local CMDWIN = 0x100000
local MODIFY = 0x200000
local EXFLAGS = 0x400000
local FILES = (XFILE+EXTRA)
local WORD1 = (EXTRA+NOSPC)
local FILE1 = (FILES+NOSPC)
return {
  {
    command='append',
    flags=BANG+RANGE+ZEROR+TRLBAR+CMDWIN+MODIFY,
    func='ex_append',
  },
  {
    command='abbreviate',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_abbreviate',
  },
  {
    command='abclear',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='ex_abclear',
  },
  {
    command='aboveleft',
    flags=NEEDARG+EXTRA+NOTRLCOM,
    func='ex_wrongmodifier',
  },
  {
    command='all',
    flags=BANG+RANGE+NOTADR+COUNT+TRLBAR,
    func='ex_all',
  },
  {
    command='amenu',
    flags=RANGE+NOTADR+ZEROR+EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='anoremenu',
    flags=RANGE+NOTADR+ZEROR+EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='args',
    flags=BANG+FILES+EDITCMD+ARGOPT+TRLBAR,
    func='ex_args',
  },
  {
    command='argadd',
    flags=BANG+NEEDARG+RANGE+NOTADR+ZEROR+FILES+TRLBAR,
    func='ex_argadd',
  },
  {
    command='argdelete',
    flags=BANG+RANGE+NOTADR+FILES+TRLBAR,
    func='ex_argdelete',
  },
  {
    command='argdo',
    flags=BANG+NEEDARG+EXTRA+NOTRLCOM,
    func='ex_listdo',
  },
  {
    command='argedit',
    flags=BANG+NEEDARG+RANGE+NOTADR+FILE1+EDITCMD+ARGOPT+TRLBAR,
    func='ex_argedit',
  },
  {
    command='argglobal',
    flags=BANG+FILES+EDITCMD+ARGOPT+TRLBAR,
    func='ex_args',
  },
  {
    command='arglocal',
    flags=BANG+FILES+EDITCMD+ARGOPT+TRLBAR,
    func='ex_args',
  },
  {
    command='argument',
    flags=BANG+RANGE+NOTADR+COUNT+EXTRA+EDITCMD+ARGOPT+TRLBAR,
    func='ex_argument',
  },
  {
    command='ascii',
    flags=TRLBAR+SBOXOK+CMDWIN,
    func='do_ascii',
  },
  {
    command='autocmd',
    flags=BANG+EXTRA+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_autocmd',
  },
  {
    command='augroup',
    flags=BANG+WORD1+TRLBAR+CMDWIN,
    func='ex_autocmd',
  },
  {
    command='aunmenu',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='buffer',
    flags=BANG+RANGE+NOTADR+BUFNAME+BUFUNL+COUNT+EXTRA+TRLBAR,
    func='ex_buffer',
  },
  {
    command='bNext',
    flags=BANG+RANGE+NOTADR+COUNT+TRLBAR,
    func='ex_bprevious',
  },
  {
    command='ball',
    flags=RANGE+NOTADR+COUNT+TRLBAR,
    func='ex_buffer_all',
  },
  {
    command='badd',
    flags=NEEDARG+FILE1+EDITCMD+TRLBAR+CMDWIN,
    func='ex_edit',
  },
  {
    command='bdelete',
    flags=BANG+RANGE+NOTADR+BUFNAME+COUNT+EXTRA+TRLBAR,
    func='ex_bunload',
  },
  {
    command='behave',
    flags=NEEDARG+WORD1+TRLBAR+CMDWIN,
    func='ex_behave',
  },
  {
    command='belowright',
    flags=NEEDARG+EXTRA+NOTRLCOM,
    func='ex_wrongmodifier',
  },
  {
    command='bfirst',
    flags=BANG+RANGE+NOTADR+TRLBAR,
    func='ex_brewind',
  },
  {
    command='blast',
    flags=BANG+RANGE+NOTADR+TRLBAR,
    func='ex_blast',
  },
  {
    command='bmodified',
    flags=BANG+RANGE+NOTADR+COUNT+TRLBAR,
    func='ex_bmodified',
  },
  {
    command='bnext',
    flags=BANG+RANGE+NOTADR+COUNT+TRLBAR,
    func='ex_bnext',
  },
  {
    command='botright',
    flags=NEEDARG+EXTRA+NOTRLCOM,
    func='ex_wrongmodifier',
  },
  {
    command='bprevious',
    flags=BANG+RANGE+NOTADR+COUNT+TRLBAR,
    func='ex_bprevious',
  },
  {
    command='brewind',
    flags=BANG+RANGE+NOTADR+TRLBAR,
    func='ex_brewind',
  },
  {
    command='break',
    flags=TRLBAR+SBOXOK+CMDWIN,
    func='ex_break',
  },
  {
    command='breakadd',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='ex_breakadd',
  },
  {
    command='breakdel',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='ex_breakdel',
  },
  {
    command='breaklist',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='ex_breaklist',
  },
  {
    command='browse',
    flags=NEEDARG+EXTRA+NOTRLCOM+CMDWIN,
    func='ex_wrongmodifier',
  },
  {
    command='buffers',
    flags=BANG+TRLBAR+CMDWIN,
    func='buflist_list',
  },
  {
    command='bufdo',
    flags=BANG+NEEDARG+EXTRA+NOTRLCOM,
    func='ex_listdo',
  },
  {
    command='bunload',
    flags=BANG+RANGE+NOTADR+BUFNAME+COUNT+EXTRA+TRLBAR,
    func='ex_bunload',
  },
  {
    command='bwipeout',
    flags=BANG+RANGE+NOTADR+BUFNAME+BUFUNL+COUNT+EXTRA+TRLBAR,
    func='ex_bunload',
  },
  {
    command='change',
    flags=BANG+WHOLEFOLD+RANGE+COUNT+TRLBAR+CMDWIN+MODIFY,
    func='ex_change',
  },
  {
    command='cNext',
    flags=RANGE+NOTADR+COUNT+TRLBAR+BANG,
    func='ex_cnext',
  },
  {
    command='cNfile',
    flags=RANGE+NOTADR+COUNT+TRLBAR+BANG,
    func='ex_cnext',
  },
  {
    command='cabbrev',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_abbreviate',
  },
  {
    command='cabclear',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='ex_abclear',
  },
  {
    command='caddbuffer',
    flags=RANGE+NOTADR+WORD1+TRLBAR,
    func='ex_cbuffer',
  },
  {
    command='caddexpr',
    flags=NEEDARG+WORD1+NOTRLCOM+TRLBAR,
    func='ex_cexpr',
  },
  {
    command='caddfile',
    flags=TRLBAR+FILE1,
    func='ex_cfile',
  },
  {
    command='call',
    flags=RANGE+NEEDARG+EXTRA+NOTRLCOM+SBOXOK+CMDWIN,
    func='ex_call',
  },
  {
    command='catch',
    flags=EXTRA+SBOXOK+CMDWIN,
    func='ex_catch',
  },
  {
    command='cbuffer',
    flags=BANG+RANGE+NOTADR+WORD1+TRLBAR,
    func='ex_cbuffer',
  },
  {
    command='cc',
    flags=RANGE+NOTADR+COUNT+TRLBAR+BANG,
    func='ex_cc',
  },
  {
    command='cclose',
    flags=RANGE+NOTADR+COUNT+TRLBAR,
    func='ex_cclose',
  },
  {
    command='cd',
    flags=BANG+FILE1+TRLBAR+CMDWIN,
    func='ex_cd',
  },
  {
    command='center',
    flags=TRLBAR+RANGE+WHOLEFOLD+EXTRA+CMDWIN+MODIFY,
    func='ex_align',
  },
  {
    command='cexpr',
    flags=NEEDARG+WORD1+NOTRLCOM+TRLBAR+BANG,
    func='ex_cexpr',
  },
  {
    command='cfile',
    flags=TRLBAR+FILE1+BANG,
    func='ex_cfile',
  },
  {
    command='cfirst',
    flags=RANGE+NOTADR+COUNT+TRLBAR+BANG,
    func='ex_cc',
  },
  {
    command='cgetfile',
    flags=TRLBAR+FILE1,
    func='ex_cfile',
  },
  {
    command='cgetbuffer',
    flags=RANGE+NOTADR+WORD1+TRLBAR,
    func='ex_cbuffer',
  },
  {
    command='cgetexpr',
    flags=NEEDARG+WORD1+NOTRLCOM+TRLBAR,
    func='ex_cexpr',
  },
  {
    command='chdir',
    flags=BANG+FILE1+TRLBAR+CMDWIN,
    func='ex_cd',
  },
  {
    command='changes',
    flags=TRLBAR+CMDWIN,
    func='ex_changes',
  },
  {
    command='checkpath',
    flags=TRLBAR+BANG+CMDWIN,
    func='ex_checkpath',
  },
  {
    command='checktime',
    flags=RANGE+NOTADR+BUFNAME+COUNT+EXTRA+TRLBAR,
    func='ex_checktime',
  },
  {
    command='clist',
    flags=BANG+EXTRA+TRLBAR+CMDWIN,
    func='qf_list',
  },
  {
    command='clast',
    flags=RANGE+NOTADR+COUNT+TRLBAR+BANG,
    func='ex_cc',
  },
  {
    command='close',
    flags=BANG+TRLBAR+CMDWIN,
    func='ex_close',
  },
  {
    command='cmap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_map',
  },
  {
    command='cmapclear',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='ex_mapclear',
  },
  {
    command='cmenu',
    flags=RANGE+NOTADR+ZEROR+EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='cnext',
    flags=RANGE+NOTADR+COUNT+TRLBAR+BANG,
    func='ex_cnext',
  },
  {
    command='cnewer',
    flags=RANGE+NOTADR+COUNT+TRLBAR,
    func='qf_age',
  },
  {
    command='cnfile',
    flags=RANGE+NOTADR+COUNT+TRLBAR+BANG,
    func='ex_cnext',
  },
  {
    command='cnoremap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_map',
  },
  {
    command='cnoreabbrev',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_abbreviate',
  },
  {
    command='cnoremenu',
    flags=RANGE+NOTADR+ZEROR+EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='copy',
    flags=RANGE+WHOLEFOLD+EXTRA+TRLBAR+CMDWIN+MODIFY,
    func='ex_copymove',
  },
  {
    command='colder',
    flags=RANGE+NOTADR+COUNT+TRLBAR,
    func='qf_age',
  },
  {
    command='colorscheme',
    flags=WORD1+TRLBAR+CMDWIN,
    func='ex_colorscheme',
  },
  {
    command='command',
    flags=EXTRA+BANG+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_command',
  },
  {
    command='comclear',
    flags=TRLBAR+CMDWIN,
    func='ex_comclear',
  },
  {
    command='compiler',
    flags=BANG+TRLBAR+WORD1+CMDWIN,
    func='ex_compiler',
  },
  {
    command='continue',
    flags=TRLBAR+SBOXOK+CMDWIN,
    func='ex_continue',
  },
  {
    command='confirm',
    flags=NEEDARG+EXTRA+NOTRLCOM+CMDWIN,
    func='ex_wrongmodifier',
  },
  {
    command='copen',
    flags=RANGE+NOTADR+COUNT+TRLBAR,
    func='ex_copen',
  },
  {
    command='cprevious',
    flags=RANGE+NOTADR+COUNT+TRLBAR+BANG,
    func='ex_cnext',
  },
  {
    command='cpfile',
    flags=RANGE+NOTADR+COUNT+TRLBAR+BANG,
    func='ex_cnext',
  },
  {
    command='cquit',
    flags=TRLBAR+BANG,
    func='ex_cquit',
  },
  {
    command='crewind',
    flags=RANGE+NOTADR+COUNT+TRLBAR+BANG,
    func='ex_cc',
  },
  {
    command='cscope',
    flags=EXTRA+NOTRLCOM+XFILE,
    func='do_cscope',
  },
  {
    command='cstag',
    flags=BANG+TRLBAR+WORD1,
    func='do_cstag',
  },
  {
    command='cunmap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_unmap',
  },
  {
    command='cunabbrev',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_abbreviate',
  },
  {
    command='cunmenu',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='cwindow',
    flags=RANGE+NOTADR+COUNT+TRLBAR,
    func='ex_cwindow',
  },
  {
    command='delete',
    flags=RANGE+WHOLEFOLD+REGSTR+COUNT+TRLBAR+CMDWIN+MODIFY,
    func='ex_operators',
  },
  {
    command='delmarks',
    flags=BANG+EXTRA+TRLBAR+CMDWIN,
    func='ex_delmarks',
  },
  {
    command='debug',
    flags=NEEDARG+EXTRA+NOTRLCOM+SBOXOK+CMDWIN,
    func='ex_debug',
  },
  {
    command='debuggreedy',
    flags=RANGE+NOTADR+ZEROR+TRLBAR+CMDWIN,
    func='ex_debuggreedy',
  },
  {
    command='delcommand',
    flags=NEEDARG+WORD1+TRLBAR+CMDWIN,
    func='ex_delcommand',
  },
  {
    command='delfunction',
    flags=NEEDARG+WORD1+CMDWIN,
    func='ex_delfunction',
  },
  {
    command='display',
    flags=EXTRA+NOTRLCOM+TRLBAR+SBOXOK+CMDWIN,
    func='ex_display',
  },
  {
    command='diffupdate',
    flags=BANG+TRLBAR,
    func='ex_diffupdate',
  },
  {
    command='diffget',
    flags=RANGE+EXTRA+TRLBAR+MODIFY,
    func='ex_diffgetput',
  },
  {
    command='diffoff',
    flags=BANG+TRLBAR,
    func='ex_diffoff',
  },
  {
    command='diffpatch',
    flags=EXTRA+FILE1+TRLBAR+MODIFY,
    func='ex_diffpatch',
  },
  {
    command='diffput',
    flags=RANGE+EXTRA+TRLBAR,
    func='ex_diffgetput',
  },
  {
    command='diffsplit',
    flags=EXTRA+FILE1+TRLBAR,
    func='ex_diffsplit',
  },
  {
    command='diffthis',
    flags=TRLBAR,
    func='ex_diffthis',
  },
  {
    command='digraphs',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='ex_digraphs',
  },
  {
    command='djump',
    flags=BANG+RANGE+DFLALL+WHOLEFOLD+EXTRA,
    func='ex_findpat',
  },
  {
    command='dlist',
    flags=BANG+RANGE+DFLALL+WHOLEFOLD+EXTRA+CMDWIN,
    func='ex_findpat',
  },
  {
    command='doautocmd',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='ex_doautocmd',
  },
  {
    command='doautoall',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='ex_doautoall',
  },
  {
    command='drop',
    flags=FILES+EDITCMD+NEEDARG+ARGOPT+TRLBAR,
    func='ex_drop',
  },
  {
    command='dsearch',
    flags=BANG+RANGE+DFLALL+WHOLEFOLD+EXTRA+CMDWIN,
    func='ex_findpat',
  },
  {
    command='dsplit',
    flags=BANG+RANGE+DFLALL+WHOLEFOLD+EXTRA,
    func='ex_findpat',
  },
  {
    command='edit',
    flags=BANG+FILE1+EDITCMD+ARGOPT+TRLBAR,
    func='ex_edit',
  },
  {
    command='earlier',
    flags=TRLBAR+EXTRA+NOSPC+CMDWIN,
    func='ex_later',
  },
  {
    command='echo',
    flags=EXTRA+NOTRLCOM+SBOXOK+CMDWIN,
    func='ex_echo',
  },
  {
    command='echoerr',
    flags=EXTRA+NOTRLCOM+SBOXOK+CMDWIN,
    func='ex_execute',
  },
  {
    command='echohl',
    flags=EXTRA+TRLBAR+SBOXOK+CMDWIN,
    func='ex_echohl',
  },
  {
    command='echomsg',
    flags=EXTRA+NOTRLCOM+SBOXOK+CMDWIN,
    func='ex_execute',
  },
  {
    command='echon',
    flags=EXTRA+NOTRLCOM+SBOXOK+CMDWIN,
    func='ex_echo',
  },
  {
    command='else',
    flags=TRLBAR+SBOXOK+CMDWIN,
    func='ex_else',
  },
  {
    command='elseif',
    flags=EXTRA+NOTRLCOM+SBOXOK+CMDWIN,
    func='ex_else',
  },
  {
    command='emenu',
    flags=NEEDARG+EXTRA+TRLBAR+NOTRLCOM+RANGE+NOTADR+CMDWIN,
    func='ex_emenu',
  },
  {
    command='endif',
    flags=TRLBAR+SBOXOK+CMDWIN,
    func='ex_endif',
  },
  {
    command='endfunction',
    flags=TRLBAR+CMDWIN,
    func='ex_endfunction',
  },
  {
    command='endfor',
    flags=TRLBAR+SBOXOK+CMDWIN,
    func='ex_endwhile',
  },
  {
    command='endtry',
    flags=TRLBAR+SBOXOK+CMDWIN,
    func='ex_endtry',
  },
  {
    command='endwhile',
    flags=TRLBAR+SBOXOK+CMDWIN,
    func='ex_endwhile',
  },
  {
    command='enew',
    flags=BANG+TRLBAR,
    func='ex_edit',
  },
  {
    command='ex',
    flags=BANG+FILE1+EDITCMD+ARGOPT+TRLBAR,
    func='ex_edit',
  },
  {
    command='execute',
    flags=EXTRA+NOTRLCOM+SBOXOK+CMDWIN,
    func='ex_execute',
  },
  {
    command='exit',
    flags=RANGE+WHOLEFOLD+BANG+FILE1+ARGOPT+DFLALL+TRLBAR+CMDWIN,
    func='ex_exit',
  },
  {
    command='exusage',
    flags=TRLBAR,
    func='ex_exusage',
  },
  {
    command='file',
    flags=RANGE+NOTADR+ZEROR+BANG+FILE1+TRLBAR,
    func='ex_file',
  },
  {
    command='files',
    flags=BANG+TRLBAR+CMDWIN,
    func='buflist_list',
  },
  {
    command='filetype',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='ex_filetype',
  },
  {
    command='find',
    flags=RANGE+NOTADR+BANG+FILE1+EDITCMD+ARGOPT+TRLBAR,
    func='ex_find',
  },
  {
    command='finally',
    flags=TRLBAR+SBOXOK+CMDWIN,
    func='ex_finally',
  },
  {
    command='finish',
    flags=TRLBAR+SBOXOK+CMDWIN,
    func='ex_finish',
  },
  {
    command='first',
    flags=EXTRA+BANG+EDITCMD+ARGOPT+TRLBAR,
    func='ex_rewind',
  },
  {
    command='fixdel',
    flags=TRLBAR+CMDWIN,
    func='do_fixdel',
  },
  {
    command='fold',
    flags=RANGE+WHOLEFOLD+TRLBAR+SBOXOK+CMDWIN,
    func='ex_fold',
  },
  {
    command='foldclose',
    flags=RANGE+BANG+WHOLEFOLD+TRLBAR+SBOXOK+CMDWIN,
    func='ex_foldopen',
  },
  {
    command='folddoopen',
    flags=RANGE+DFLALL+NEEDARG+EXTRA+NOTRLCOM,
    func='ex_folddo',
  },
  {
    command='folddoclosed',
    flags=RANGE+DFLALL+NEEDARG+EXTRA+NOTRLCOM,
    func='ex_folddo',
  },
  {
    command='foldopen',
    flags=RANGE+BANG+WHOLEFOLD+TRLBAR+SBOXOK+CMDWIN,
    func='ex_foldopen',
  },
  {
    command='for',
    flags=EXTRA+NOTRLCOM+SBOXOK+CMDWIN,
    func='ex_while',
  },
  {
    command='function',
    flags=EXTRA+BANG+CMDWIN,
    func='ex_function',
  },
  {
    command='global',
    flags=RANGE+WHOLEFOLD+BANG+EXTRA+DFLALL+SBOXOK+CMDWIN,
    func='ex_global',
  },
  {
    command='goto',
    flags=RANGE+NOTADR+COUNT+TRLBAR+SBOXOK+CMDWIN,
    func='ex_goto',
  },
  {
    command='grep',
    flags=RANGE+NOTADR+BANG+NEEDARG+EXTRA+NOTRLCOM+TRLBAR+XFILE,
    func='ex_make',
  },
  {
    command='grepadd',
    flags=RANGE+NOTADR+BANG+NEEDARG+EXTRA+NOTRLCOM+TRLBAR+XFILE,
    func='ex_make',
  },
  {
    command='gui',
    flags=BANG+FILES+EDITCMD+ARGOPT+TRLBAR+CMDWIN,
    func='ex_gui',
  },
  {
    command='gvim',
    flags=BANG+FILES+EDITCMD+ARGOPT+TRLBAR+CMDWIN,
    func='ex_gui',
  },
  {
    command='help',
    flags=BANG+EXTRA+NOTRLCOM,
    func='ex_help',
  },
  {
    command='helpfind',
    flags=EXTRA+NOTRLCOM,
    func='ex_helpfind',
  },
  {
    command='helpgrep',
    flags=EXTRA+NOTRLCOM+NEEDARG,
    func='ex_helpgrep',
  },
  {
    command='helptags',
    flags=NEEDARG+FILES+TRLBAR+CMDWIN,
    func='ex_helptags',
  },
  {
    command='hardcopy',
    flags=RANGE+COUNT+EXTRA+TRLBAR+DFLALL+BANG,
    func='ex_hardcopy',
  },
  {
    command='highlight',
    flags=BANG+EXTRA+TRLBAR+SBOXOK+CMDWIN,
    func='ex_highlight',
  },
  {
    command='hide',
    flags=BANG+EXTRA+NOTRLCOM,
    func='ex_hide',
  },
  {
    command='history',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='ex_history',
  },
  {
    command='insert',
    flags=BANG+RANGE+TRLBAR+CMDWIN+MODIFY,
    func='ex_append',
  },
  {
    command='iabbrev',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_abbreviate',
  },
  {
    command='iabclear',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='ex_abclear',
  },
  {
    command='if',
    flags=EXTRA+NOTRLCOM+SBOXOK+CMDWIN,
    func='ex_if',
  },
  {
    command='ijump',
    flags=BANG+RANGE+DFLALL+WHOLEFOLD+EXTRA,
    func='ex_findpat',
  },
  {
    command='ilist',
    flags=BANG+RANGE+DFLALL+WHOLEFOLD+EXTRA+CMDWIN,
    func='ex_findpat',
  },
  {
    command='imap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_map',
  },
  {
    command='imapclear',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='ex_mapclear',
  },
  {
    command='imenu',
    flags=RANGE+NOTADR+ZEROR+EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='inoremap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_map',
  },
  {
    command='inoreabbrev',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_abbreviate',
  },
  {
    command='inoremenu',
    flags=RANGE+NOTADR+ZEROR+EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='intro',
    flags=TRLBAR+CMDWIN,
    func='ex_intro',
  },
  {
    command='isearch',
    flags=BANG+RANGE+DFLALL+WHOLEFOLD+EXTRA+CMDWIN,
    func='ex_findpat',
  },
  {
    command='isplit',
    flags=BANG+RANGE+DFLALL+WHOLEFOLD+EXTRA,
    func='ex_findpat',
  },
  {
    command='iunmap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_unmap',
  },
  {
    command='iunabbrev',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_abbreviate',
  },
  {
    command='iunmenu',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='join',
    flags=BANG+RANGE+WHOLEFOLD+COUNT+EXFLAGS+TRLBAR+CMDWIN+MODIFY,
    func='ex_join',
  },
  {
    command='jumps',
    flags=TRLBAR+CMDWIN,
    func='ex_jumps',
  },
  {
    command='k',
    flags=RANGE+WORD1+TRLBAR+SBOXOK+CMDWIN,
    func='ex_mark',
  },
  {
    command='keepmarks',
    flags=NEEDARG+EXTRA+NOTRLCOM,
    func='ex_wrongmodifier',
  },
  {
    command='keepjumps',
    flags=NEEDARG+EXTRA+NOTRLCOM,
    func='ex_wrongmodifier',
  },
  {
    command='keeppatterns',
    flags=NEEDARG+EXTRA+NOTRLCOM,
    func='ex_wrongmodifier',
  },
  {
    command='keepalt',
    flags=NEEDARG+EXTRA+NOTRLCOM,
    func='ex_wrongmodifier',
  },
  {
    command='list',
    flags=RANGE+WHOLEFOLD+COUNT+EXFLAGS+TRLBAR+CMDWIN,
    func='ex_print',
  },
  {
    command='lNext',
    flags=RANGE+NOTADR+COUNT+TRLBAR+BANG,
    func='ex_cnext',
  },
  {
    command='lNfile',
    flags=RANGE+NOTADR+COUNT+TRLBAR+BANG,
    func='ex_cnext',
  },
  {
    command='last',
    flags=EXTRA+BANG+EDITCMD+ARGOPT+TRLBAR,
    func='ex_last',
  },
  {
    command='language',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='ex_language',
  },
  {
    command='laddexpr',
    flags=NEEDARG+WORD1+NOTRLCOM+TRLBAR,
    func='ex_cexpr',
  },
  {
    command='laddbuffer',
    flags=RANGE+NOTADR+WORD1+TRLBAR,
    func='ex_cbuffer',
  },
  {
    command='laddfile',
    flags=TRLBAR+FILE1,
    func='ex_cfile',
  },
  {
    command='later',
    flags=TRLBAR+EXTRA+NOSPC+CMDWIN,
    func='ex_later',
  },
  {
    command='lbuffer',
    flags=BANG+RANGE+NOTADR+WORD1+TRLBAR,
    func='ex_cbuffer',
  },
  {
    command='lcd',
    flags=BANG+FILE1+TRLBAR+CMDWIN,
    func='ex_cd',
  },
  {
    command='lchdir',
    flags=BANG+FILE1+TRLBAR+CMDWIN,
    func='ex_cd',
  },
  {
    command='lclose',
    flags=RANGE+NOTADR+COUNT+TRLBAR,
    func='ex_cclose',
  },
  {
    command='lcscope',
    flags=EXTRA+NOTRLCOM+XFILE,
    func='do_cscope',
  },
  {
    command='left',
    flags=TRLBAR+RANGE+WHOLEFOLD+EXTRA+CMDWIN+MODIFY,
    func='ex_align',
  },
  {
    command='leftabove',
    flags=NEEDARG+EXTRA+NOTRLCOM,
    func='ex_wrongmodifier',
  },
  {
    command='let',
    flags=EXTRA+NOTRLCOM+SBOXOK+CMDWIN,
    func='ex_let',
  },
  {
    command='lexpr',
    flags=NEEDARG+WORD1+NOTRLCOM+TRLBAR+BANG,
    func='ex_cexpr',
  },
  {
    command='lfile',
    flags=TRLBAR+FILE1+BANG,
    func='ex_cfile',
  },
  {
    command='lfirst',
    flags=RANGE+NOTADR+COUNT+TRLBAR+BANG,
    func='ex_cc',
  },
  {
    command='lgetfile',
    flags=TRLBAR+FILE1,
    func='ex_cfile',
  },
  {
    command='lgetbuffer',
    flags=RANGE+NOTADR+WORD1+TRLBAR,
    func='ex_cbuffer',
  },
  {
    command='lgetexpr',
    flags=NEEDARG+WORD1+NOTRLCOM+TRLBAR,
    func='ex_cexpr',
  },
  {
    command='lgrep',
    flags=RANGE+NOTADR+BANG+NEEDARG+EXTRA+NOTRLCOM+TRLBAR+XFILE,
    func='ex_make',
  },
  {
    command='lgrepadd',
    flags=RANGE+NOTADR+BANG+NEEDARG+EXTRA+NOTRLCOM+TRLBAR+XFILE,
    func='ex_make',
  },
  {
    command='lhelpgrep',
    flags=EXTRA+NOTRLCOM+NEEDARG,
    func='ex_helpgrep',
  },
  {
    command='ll',
    flags=RANGE+NOTADR+COUNT+TRLBAR+BANG,
    func='ex_cc',
  },
  {
    command='llast',
    flags=RANGE+NOTADR+COUNT+TRLBAR+BANG,
    func='ex_cc',
  },
  {
    command='llist',
    flags=BANG+EXTRA+TRLBAR+CMDWIN,
    func='qf_list',
  },
  {
    command='lmap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_map',
  },
  {
    command='lmapclear',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='ex_mapclear',
  },
  {
    command='lmake',
    flags=BANG+EXTRA+NOTRLCOM+TRLBAR+XFILE,
    func='ex_make',
  },
  {
    command='lnoremap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_map',
  },
  {
    command='lnext',
    flags=RANGE+NOTADR+COUNT+TRLBAR+BANG,
    func='ex_cnext',
  },
  {
    command='lnewer',
    flags=RANGE+NOTADR+COUNT+TRLBAR,
    func='qf_age',
  },
  {
    command='lnfile',
    flags=RANGE+NOTADR+COUNT+TRLBAR+BANG,
    func='ex_cnext',
  },
  {
    command='loadview',
    flags=FILE1+TRLBAR,
    func='ex_loadview',
  },
  {
    command='loadkeymap',
    flags=CMDWIN,
    func='ex_loadkeymap',
  },
  {
    command='lockmarks',
    flags=NEEDARG+EXTRA+NOTRLCOM,
    func='ex_wrongmodifier',
  },
  {
    command='lockvar',
    flags=BANG+EXTRA+NEEDARG+SBOXOK+CMDWIN,
    func='ex_lockvar',
  },
  {
    command='lolder',
    flags=RANGE+NOTADR+COUNT+TRLBAR,
    func='qf_age',
  },
  {
    command='lopen',
    flags=RANGE+NOTADR+COUNT+TRLBAR,
    func='ex_copen',
  },
  {
    command='lprevious',
    flags=RANGE+NOTADR+COUNT+TRLBAR+BANG,
    func='ex_cnext',
  },
  {
    command='lpfile',
    flags=RANGE+NOTADR+COUNT+TRLBAR+BANG,
    func='ex_cnext',
  },
  {
    command='lrewind',
    flags=RANGE+NOTADR+COUNT+TRLBAR+BANG,
    func='ex_cc',
  },
  {
    command='ltag',
    flags=NOTADR+TRLBAR+BANG+WORD1,
    func='ex_tag',
  },
  {
    command='lunmap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_unmap',
  },
  {
    command='lvimgrep',
    flags=RANGE+NOTADR+BANG+NEEDARG+EXTRA+NOTRLCOM+TRLBAR+XFILE,
    func='ex_vimgrep',
  },
  {
    command='lvimgrepadd',
    flags=RANGE+NOTADR+BANG+NEEDARG+EXTRA+NOTRLCOM+TRLBAR+XFILE,
    func='ex_vimgrep',
  },
  {
    command='lwindow',
    flags=RANGE+NOTADR+COUNT+TRLBAR,
    func='ex_cwindow',
  },
  {
    command='ls',
    flags=BANG+TRLBAR+CMDWIN,
    func='buflist_list',
  },
  {
    command='move',
    flags=RANGE+WHOLEFOLD+EXTRA+TRLBAR+CMDWIN+MODIFY,
    func='ex_copymove',
  },
  {
    command='mark',
    flags=RANGE+WORD1+TRLBAR+SBOXOK+CMDWIN,
    func='ex_mark',
  },
  {
    command='make',
    flags=BANG+EXTRA+NOTRLCOM+TRLBAR+XFILE,
    func='ex_make',
  },
  {
    command='map',
    flags=BANG+EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_map',
  },
  {
    command='mapclear',
    flags=EXTRA+BANG+TRLBAR+CMDWIN,
    func='ex_mapclear',
  },
  {
    command='marks',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='do_marks',
  },
  {
    command='match',
    flags=RANGE+NOTADR+EXTRA+CMDWIN,
    func='ex_match',
  },
  {
    command='menu',
    flags=RANGE+NOTADR+ZEROR+BANG+EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='menutranslate',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menutranslate',
  },
  {
    command='messages',
    flags=TRLBAR+CMDWIN,
    func='ex_messages',
  },
  {
    command='mkexrc',
    flags=BANG+FILE1+TRLBAR+CMDWIN,
    func='ex_mkrc',
  },
  {
    command='mksession',
    flags=BANG+FILE1+TRLBAR,
    func='ex_mkrc',
  },
  {
    command='mkspell',
    flags=BANG+NEEDARG+EXTRA+NOTRLCOM+TRLBAR+XFILE,
    func='ex_mkspell',
  },
  {
    command='mkvimrc',
    flags=BANG+FILE1+TRLBAR+CMDWIN,
    func='ex_mkrc',
  },
  {
    command='mkview',
    flags=BANG+FILE1+TRLBAR,
    func='ex_mkrc',
  },
  {
    command='mode',
    flags=WORD1+TRLBAR+CMDWIN,
    func='ex_mode',
  },
  {
    command='next',
    flags=RANGE+NOTADR+BANG+FILES+EDITCMD+ARGOPT+TRLBAR,
    func='ex_next',
  },
  {
    command='nbkey',
    flags=EXTRA+NOTADR+NEEDARG,
    func='ex_nbkey',
  },
  {
    command='nbclose',
    flags=TRLBAR+CMDWIN,
    func='ex_nbclose',
  },
  {
    command='nbstart',
    flags=WORD1+TRLBAR+CMDWIN,
    func='ex_nbstart',
  },
  {
    command='new',
    flags=BANG+FILE1+RANGE+NOTADR+EDITCMD+ARGOPT+TRLBAR,
    func='ex_splitview',
  },
  {
    command='nmap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_map',
  },
  {
    command='nmapclear',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='ex_mapclear',
  },
  {
    command='nmenu',
    flags=RANGE+NOTADR+ZEROR+EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='nnoremap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_map',
  },
  {
    command='nnoremenu',
    flags=RANGE+NOTADR+ZEROR+EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='noremap',
    flags=BANG+EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_map',
  },
  {
    command='noautocmd',
    flags=NEEDARG+EXTRA+NOTRLCOM,
    func='ex_wrongmodifier',
  },
  {
    command='nohlsearch',
    flags=TRLBAR+SBOXOK+CMDWIN,
    func='ex_nohlsearch',
  },
  {
    command='noreabbrev',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_abbreviate',
  },
  {
    command='noremenu',
    flags=RANGE+NOTADR+ZEROR+BANG+EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='noswapfile',
    flags=NEEDARG+EXTRA+NOTRLCOM,
    func='ex_wrongmodifier',
  },
  {
    command='normal',
    flags=RANGE+BANG+EXTRA+NEEDARG+NOTRLCOM+USECTRLV+SBOXOK+CMDWIN,
    func='ex_normal',
  },
  {
    command='number',
    flags=RANGE+WHOLEFOLD+COUNT+EXFLAGS+TRLBAR+CMDWIN,
    func='ex_print',
  },
  {
    command='nunmap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_unmap',
  },
  {
    command='nunmenu',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='open',
    flags=RANGE+BANG+EXTRA,
    func='ex_open',
  },
  {
    command='oldfiles',
    flags=BANG+TRLBAR+SBOXOK+CMDWIN,
    func='ex_oldfiles',
  },
  {
    command='omap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_map',
  },
  {
    command='omapclear',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='ex_mapclear',
  },
  {
    command='omenu',
    flags=RANGE+NOTADR+ZEROR+EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='only',
    flags=BANG+TRLBAR,
    func='ex_only',
  },
  {
    command='onoremap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_map',
  },
  {
    command='onoremenu',
    flags=RANGE+NOTADR+ZEROR+EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='options',
    flags=TRLBAR,
    func='ex_options',
  },
  {
    command='ounmap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_unmap',
  },
  {
    command='ounmenu',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='ownsyntax',
    flags=EXTRA+NOTRLCOM+SBOXOK+CMDWIN,
    func='ex_ownsyntax',
  },
  {
    command='print',
    flags=RANGE+WHOLEFOLD+COUNT+EXFLAGS+TRLBAR+CMDWIN+SBOXOK,
    func='ex_print',
  },
  {
    command='pclose',
    flags=BANG+TRLBAR,
    func='ex_pclose',
  },
  {
    command='pedit',
    flags=BANG+FILE1+EDITCMD+ARGOPT+TRLBAR,
    func='ex_pedit',
  },
  {
    command='pop',
    flags=RANGE+NOTADR+BANG+COUNT+TRLBAR+ZEROR,
    func='ex_tag',
  },
  {
    command='popup',
    flags=NEEDARG+EXTRA+BANG+TRLBAR+NOTRLCOM+CMDWIN,
    func='ex_popup',
  },
  {
    command='ppop',
    flags=RANGE+NOTADR+BANG+COUNT+TRLBAR+ZEROR,
    func='ex_ptag',
  },
  {
    command='preserve',
    flags=TRLBAR,
    func='ex_preserve',
  },
  {
    command='previous',
    flags=EXTRA+RANGE+NOTADR+COUNT+BANG+EDITCMD+ARGOPT+TRLBAR,
    func='ex_previous',
  },
  {
    command='promptfind',
    flags=EXTRA+NOTRLCOM+CMDWIN,
    func='gui_mch_find_dialog',
  },
  {
    command='promptrepl',
    flags=EXTRA+NOTRLCOM+CMDWIN,
    func='gui_mch_replace_dialog',
  },
  {
    command='profile',
    flags=BANG+EXTRA+TRLBAR+CMDWIN,
    func='ex_profile',
  },
  {
    command='profdel',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='ex_breakdel',
  },
  {
    command='psearch',
    flags=BANG+RANGE+WHOLEFOLD+DFLALL+EXTRA,
    func='ex_psearch',
  },
  {
    command='ptag',
    flags=RANGE+NOTADR+BANG+WORD1+TRLBAR+ZEROR,
    func='ex_ptag',
  },
  {
    command='ptNext',
    flags=RANGE+NOTADR+BANG+TRLBAR+ZEROR,
    func='ex_ptag',
  },
  {
    command='ptfirst',
    flags=RANGE+NOTADR+BANG+TRLBAR+ZEROR,
    func='ex_ptag',
  },
  {
    command='ptjump',
    flags=BANG+TRLBAR+WORD1,
    func='ex_ptag',
  },
  {
    command='ptlast',
    flags=BANG+TRLBAR,
    func='ex_ptag',
  },
  {
    command='ptnext',
    flags=RANGE+NOTADR+BANG+TRLBAR+ZEROR,
    func='ex_ptag',
  },
  {
    command='ptprevious',
    flags=RANGE+NOTADR+BANG+TRLBAR+ZEROR,
    func='ex_ptag',
  },
  {
    command='ptrewind',
    flags=RANGE+NOTADR+BANG+TRLBAR+ZEROR,
    func='ex_ptag',
  },
  {
    command='ptselect',
    flags=BANG+TRLBAR+WORD1,
    func='ex_ptag',
  },
  {
    command='put',
    flags=RANGE+WHOLEFOLD+BANG+REGSTR+TRLBAR+ZEROR+CMDWIN+MODIFY,
    func='ex_put',
  },
  {
    command='pwd',
    flags=TRLBAR+CMDWIN,
    func='ex_pwd',
  },
  {
    command='python',
    flags=RANGE+EXTRA+NEEDARG+CMDWIN,
    func='ex_python',
  },
  {
    command='pydo',
    flags=RANGE+DFLALL+EXTRA+NEEDARG+CMDWIN,
    func='ex_pydo',
  },
  {
    command='pyfile',
    flags=RANGE+FILE1+NEEDARG+CMDWIN,
    func='ex_pyfile',
  },
  {
    command='quit',
    flags=BANG+TRLBAR+CMDWIN,
    func='ex_quit',
  },
  {
    command='quitall',
    flags=BANG+TRLBAR,
    func='ex_quit_all',
  },
  {
    command='qall',
    flags=BANG+TRLBAR+CMDWIN,
    func='ex_quit_all',
  },
  {
    command='read',
    flags=BANG+RANGE+WHOLEFOLD+FILE1+ARGOPT+TRLBAR+ZEROR+CMDWIN+MODIFY,
    func='ex_read',
  },
  {
    command='recover',
    flags=BANG+FILE1+TRLBAR,
    func='ex_recover',
  },
  {
    command='redo',
    flags=TRLBAR+CMDWIN,
    func='ex_redo',
  },
  {
    command='redir',
    flags=BANG+FILES+TRLBAR+CMDWIN,
    func='ex_redir',
  },
  {
    command='redraw',
    flags=BANG+TRLBAR+CMDWIN,
    func='ex_redraw',
  },
  {
    command='redrawstatus',
    flags=BANG+TRLBAR+CMDWIN,
    func='ex_redrawstatus',
  },
  {
    command='registers',
    flags=EXTRA+NOTRLCOM+TRLBAR+CMDWIN,
    func='ex_display',
  },
  {
    command='resize',
    flags=RANGE+NOTADR+TRLBAR+WORD1,
    func='ex_resize',
  },
  {
    command='retab',
    flags=TRLBAR+RANGE+WHOLEFOLD+DFLALL+BANG+WORD1+CMDWIN+MODIFY,
    func='ex_retab',
  },
  {
    command='return',
    flags=EXTRA+NOTRLCOM+SBOXOK+CMDWIN,
    func='ex_return',
  },
  {
    command='rewind',
    flags=EXTRA+BANG+EDITCMD+ARGOPT+TRLBAR,
    func='ex_rewind',
  },
  {
    command='right',
    flags=TRLBAR+RANGE+WHOLEFOLD+EXTRA+CMDWIN+MODIFY,
    func='ex_align',
  },
  {
    command='rightbelow',
    flags=NEEDARG+EXTRA+NOTRLCOM,
    func='ex_wrongmodifier',
  },
  {
    command='runtime',
    flags=BANG+NEEDARG+FILES+TRLBAR+SBOXOK+CMDWIN,
    func='ex_runtime',
  },
  {
    command='rundo',
    flags=NEEDARG+FILE1,
    func='ex_rundo',
  },
  {
    command='rviminfo',
    flags=BANG+FILE1+TRLBAR+CMDWIN,
    func='ex_viminfo',
  },
  {
    command='substitute',
    flags=RANGE+WHOLEFOLD+EXTRA+CMDWIN,
    func='do_sub',
  },
  {
    command='sNext',
    flags=EXTRA+RANGE+NOTADR+COUNT+BANG+EDITCMD+ARGOPT+TRLBAR,
    func='ex_previous',
  },
  {
    command='sargument',
    flags=BANG+RANGE+NOTADR+COUNT+EXTRA+EDITCMD+ARGOPT+TRLBAR,
    func='ex_argument',
  },
  {
    command='sall',
    flags=BANG+RANGE+NOTADR+COUNT+TRLBAR,
    func='ex_all',
  },
  {
    command='sandbox',
    flags=NEEDARG+EXTRA+NOTRLCOM,
    func='ex_wrongmodifier',
  },
  {
    command='saveas',
    flags=BANG+DFLALL+FILE1+ARGOPT+CMDWIN+TRLBAR,
    func='ex_write',
  },
  {
    command='sbuffer',
    flags=BANG+RANGE+NOTADR+BUFNAME+BUFUNL+COUNT+EXTRA+TRLBAR,
    func='ex_buffer',
  },
  {
    command='sbNext',
    flags=RANGE+NOTADR+COUNT+TRLBAR,
    func='ex_bprevious',
  },
  {
    command='sball',
    flags=RANGE+NOTADR+COUNT+TRLBAR,
    func='ex_buffer_all',
  },
  {
    command='sbfirst',
    flags=TRLBAR,
    func='ex_brewind',
  },
  {
    command='sblast',
    flags=TRLBAR,
    func='ex_blast',
  },
  {
    command='sbmodified',
    flags=RANGE+NOTADR+COUNT+TRLBAR,
    func='ex_bmodified',
  },
  {
    command='sbnext',
    flags=RANGE+NOTADR+COUNT+TRLBAR,
    func='ex_bnext',
  },
  {
    command='sbprevious',
    flags=RANGE+NOTADR+COUNT+TRLBAR,
    func='ex_bprevious',
  },
  {
    command='sbrewind',
    flags=TRLBAR,
    func='ex_brewind',
  },
  {
    command='scriptnames',
    flags=TRLBAR+CMDWIN,
    func='ex_scriptnames',
  },
  {
    command='scriptencoding',
    flags=WORD1+TRLBAR+CMDWIN,
    func='ex_scriptencoding',
  },
  {
    command='scscope',
    flags=EXTRA+NOTRLCOM,
    func='do_scscope',
  },
  {
    command='set',
    flags=TRLBAR+EXTRA+CMDWIN+SBOXOK,
    func='ex_set',
  },
  {
    command='setfiletype',
    flags=TRLBAR+EXTRA+NEEDARG+CMDWIN,
    func='ex_setfiletype',
  },
  {
    command='setglobal',
    flags=TRLBAR+EXTRA+CMDWIN+SBOXOK,
    func='ex_set',
  },
  {
    command='setlocal',
    flags=TRLBAR+EXTRA+CMDWIN+SBOXOK,
    func='ex_set',
  },
  {
    command='sfind',
    flags=BANG+FILE1+RANGE+NOTADR+EDITCMD+ARGOPT+TRLBAR,
    func='ex_splitview',
  },
  {
    command='sfirst',
    flags=EXTRA+BANG+EDITCMD+ARGOPT+TRLBAR,
    func='ex_rewind',
  },
  {
    command='simalt',
    flags=NEEDARG+WORD1+TRLBAR+CMDWIN,
    func='ex_simalt',
  },
  {
    command='sign',
    flags=NEEDARG+RANGE+NOTADR+EXTRA+CMDWIN,
    func='ex_sign',
  },
  {
    command='silent',
    flags=NEEDARG+EXTRA+BANG+NOTRLCOM+SBOXOK+CMDWIN,
    func='ex_wrongmodifier',
  },
  {
    command='sleep',
    flags=RANGE+NOTADR+COUNT+EXTRA+TRLBAR+CMDWIN,
    func='ex_sleep',
  },
  {
    command='slast',
    flags=EXTRA+BANG+EDITCMD+ARGOPT+TRLBAR,
    func='ex_last',
  },
  {
    command='smagic',
    flags=RANGE+WHOLEFOLD+EXTRA+CMDWIN,
    func='ex_submagic',
  },
  {
    command='smap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_map',
  },
  {
    command='smapclear',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='ex_mapclear',
  },
  {
    command='smenu',
    flags=RANGE+NOTADR+ZEROR+EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='snext',
    flags=RANGE+NOTADR+BANG+FILES+EDITCMD+ARGOPT+TRLBAR,
    func='ex_next',
  },
  {
    command='snomagic',
    flags=RANGE+WHOLEFOLD+EXTRA+CMDWIN,
    func='ex_submagic',
  },
  {
    command='snoremap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_map',
  },
  {
    command='snoremenu',
    flags=RANGE+NOTADR+ZEROR+EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='source',
    flags=BANG+FILE1+TRLBAR+SBOXOK+CMDWIN,
    func='ex_source',
  },
  {
    command='sort',
    flags=RANGE+DFLALL+WHOLEFOLD+BANG+EXTRA+NOTRLCOM+MODIFY,
    func='ex_sort',
  },
  {
    command='split',
    flags=BANG+FILE1+RANGE+NOTADR+EDITCMD+ARGOPT+TRLBAR,
    func='ex_splitview',
  },
  {
    command='spellgood',
    flags=BANG+RANGE+NOTADR+NEEDARG+EXTRA+TRLBAR,
    func='ex_spell',
  },
  {
    command='spelldump',
    flags=BANG+TRLBAR,
    func='ex_spelldump',
  },
  {
    command='spellinfo',
    flags=TRLBAR,
    func='ex_spellinfo',
  },
  {
    command='spellrepall',
    flags=TRLBAR,
    func='ex_spellrepall',
  },
  {
    command='spellundo',
    flags=BANG+RANGE+NOTADR+NEEDARG+EXTRA+TRLBAR,
    func='ex_spell',
  },
  {
    command='spellwrong',
    flags=BANG+RANGE+NOTADR+NEEDARG+EXTRA+TRLBAR,
    func='ex_spell',
  },
  {
    command='sprevious',
    flags=EXTRA+RANGE+NOTADR+COUNT+BANG+EDITCMD+ARGOPT+TRLBAR,
    func='ex_previous',
  },
  {
    command='srewind',
    flags=EXTRA+BANG+EDITCMD+ARGOPT+TRLBAR,
    func='ex_rewind',
  },
  {
    command='stop',
    flags=TRLBAR+BANG+CMDWIN,
    func='ex_stop',
  },
  {
    command='stag',
    flags=RANGE+NOTADR+BANG+WORD1+TRLBAR+ZEROR,
    func='ex_stag',
  },
  {
    command='startinsert',
    flags=BANG+TRLBAR+CMDWIN,
    func='ex_startinsert',
  },
  {
    command='startgreplace',
    flags=BANG+TRLBAR+CMDWIN,
    func='ex_startinsert',
  },
  {
    command='startreplace',
    flags=BANG+TRLBAR+CMDWIN,
    func='ex_startinsert',
  },
  {
    command='stopinsert',
    flags=BANG+TRLBAR+CMDWIN,
    func='ex_stopinsert',
  },
  {
    command='stjump',
    flags=BANG+TRLBAR+WORD1,
    func='ex_stag',
  },
  {
    command='stselect',
    flags=BANG+TRLBAR+WORD1,
    func='ex_stag',
  },
  {
    command='sunhide',
    flags=RANGE+NOTADR+COUNT+TRLBAR,
    func='ex_buffer_all',
  },
  {
    command='sunmap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_unmap',
  },
  {
    command='sunmenu',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='suspend',
    flags=TRLBAR+BANG+CMDWIN,
    func='ex_stop',
  },
  {
    command='sview',
    flags=BANG+FILE1+RANGE+NOTADR+EDITCMD+ARGOPT+TRLBAR,
    func='ex_splitview',
  },
  {
    command='swapname',
    flags=TRLBAR+CMDWIN,
    func='ex_swapname',
  },
  {
    command='syntax',
    flags=EXTRA+NOTRLCOM+CMDWIN,
    func='ex_syntax',
  },
  {
    command='syntime',
    flags=NEEDARG+WORD1+TRLBAR+CMDWIN,
    func='ex_syntime',
  },
  {
    command='syncbind',
    flags=TRLBAR,
    func='ex_syncbind',
  },
  {
    command='t',
    flags=RANGE+WHOLEFOLD+EXTRA+TRLBAR+CMDWIN+MODIFY,
    func='ex_copymove',
  },
  {
    command='tNext',
    flags=RANGE+NOTADR+BANG+TRLBAR+ZEROR,
    func='ex_tag',
  },
  {
    command='tag',
    flags=RANGE+NOTADR+BANG+WORD1+TRLBAR+ZEROR,
    func='ex_tag',
  },
  {
    command='tags',
    flags=TRLBAR+CMDWIN,
    func='do_tags',
  },
  {
    command='tab',
    flags=NEEDARG+EXTRA+NOTRLCOM,
    func='ex_wrongmodifier',
  },
  {
    command='tabclose',
    flags=RANGE+NOTADR+COUNT+BANG+TRLBAR+CMDWIN,
    func='ex_tabclose',
  },
  {
    command='tabdo',
    flags=NEEDARG+EXTRA+NOTRLCOM,
    func='ex_listdo',
  },
  {
    command='tabedit',
    flags=BANG+FILE1+RANGE+NOTADR+ZEROR+EDITCMD+ARGOPT+TRLBAR,
    func='ex_splitview',
  },
  {
    command='tabfind',
    flags=BANG+FILE1+RANGE+NOTADR+ZEROR+EDITCMD+ARGOPT+NEEDARG+TRLBAR,
    func='ex_splitview',
  },
  {
    command='tabfirst',
    flags=TRLBAR,
    func='ex_tabnext',
  },
  {
    command='tabmove',
    flags=RANGE+NOTADR+ZEROR+EXTRA+NOSPC+TRLBAR,
    func='ex_tabmove',
  },
  {
    command='tablast',
    flags=TRLBAR,
    func='ex_tabnext',
  },
  {
    command='tabnext',
    flags=RANGE+NOTADR+COUNT+TRLBAR,
    func='ex_tabnext',
  },
  {
    command='tabnew',
    flags=BANG+FILE1+RANGE+NOTADR+ZEROR+EDITCMD+ARGOPT+TRLBAR,
    func='ex_splitview',
  },
  {
    command='tabonly',
    flags=BANG+TRLBAR+CMDWIN,
    func='ex_tabonly',
  },
  {
    command='tabprevious',
    flags=RANGE+NOTADR+COUNT+TRLBAR,
    func='ex_tabnext',
  },
  {
    command='tabNext',
    flags=RANGE+NOTADR+COUNT+TRLBAR,
    func='ex_tabnext',
  },
  {
    command='tabrewind',
    flags=TRLBAR,
    func='ex_tabnext',
  },
  {
    command='tabs',
    flags=TRLBAR+CMDWIN,
    func='ex_tabs',
  },
  {
    command='tearoff',
    flags=NEEDARG+EXTRA+TRLBAR+NOTRLCOM+CMDWIN,
    func='ex_tearoff',
  },
  {
    command='tfirst',
    flags=RANGE+NOTADR+BANG+TRLBAR+ZEROR,
    func='ex_tag',
  },
  {
    command='throw',
    flags=EXTRA+NEEDARG+SBOXOK+CMDWIN,
    func='ex_throw',
  },
  {
    command='tjump',
    flags=BANG+TRLBAR+WORD1,
    func='ex_tag',
  },
  {
    command='tlast',
    flags=BANG+TRLBAR,
    func='ex_tag',
  },
  {
    command='tmenu',
    flags=RANGE+NOTADR+ZEROR+EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='tnext',
    flags=RANGE+NOTADR+BANG+TRLBAR+ZEROR,
    func='ex_tag',
  },
  {
    command='topleft',
    flags=NEEDARG+EXTRA+NOTRLCOM,
    func='ex_wrongmodifier',
  },
  {
    command='tprevious',
    flags=RANGE+NOTADR+BANG+TRLBAR+ZEROR,
    func='ex_tag',
  },
  {
    command='trewind',
    flags=RANGE+NOTADR+BANG+TRLBAR+ZEROR,
    func='ex_tag',
  },
  {
    command='try',
    flags=TRLBAR+SBOXOK+CMDWIN,
    func='ex_try',
  },
  {
    command='tselect',
    flags=BANG+TRLBAR+WORD1,
    func='ex_tag',
  },
  {
    command='tunmenu',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='undo',
    flags=RANGE+NOTADR+COUNT+ZEROR+TRLBAR+CMDWIN,
    func='ex_undo',
  },
  {
    command='undojoin',
    flags=TRLBAR+CMDWIN,
    func='ex_undojoin',
  },
  {
    command='undolist',
    flags=TRLBAR+CMDWIN,
    func='ex_undolist',
  },
  {
    command='unabbreviate',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_abbreviate',
  },
  {
    command='unhide',
    flags=RANGE+NOTADR+COUNT+TRLBAR,
    func='ex_buffer_all',
  },
  {
    command='unlet',
    flags=BANG+EXTRA+NEEDARG+SBOXOK+CMDWIN,
    func='ex_unlet',
  },
  {
    command='unlockvar',
    flags=BANG+EXTRA+NEEDARG+SBOXOK+CMDWIN,
    func='ex_lockvar',
  },
  {
    command='unmap',
    flags=BANG+EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_unmap',
  },
  {
    command='unmenu',
    flags=BANG+EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='unsilent',
    flags=NEEDARG+EXTRA+NOTRLCOM+SBOXOK+CMDWIN,
    func='ex_wrongmodifier',
  },
  {
    command='update',
    flags=RANGE+WHOLEFOLD+BANG+FILE1+ARGOPT+DFLALL+TRLBAR,
    func='ex_update',
  },
  {
    command='vglobal',
    flags=RANGE+WHOLEFOLD+EXTRA+DFLALL+CMDWIN,
    func='ex_global',
  },
  {
    command='version',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='ex_version',
  },
  {
    command='verbose',
    flags=NEEDARG+RANGE+NOTADR+EXTRA+NOTRLCOM+SBOXOK+CMDWIN,
    func='ex_wrongmodifier',
  },
  {
    command='vertical',
    flags=NEEDARG+EXTRA+NOTRLCOM,
    func='ex_wrongmodifier',
  },
  {
    command='visual',
    flags=BANG+FILE1+EDITCMD+ARGOPT+TRLBAR,
    func='ex_edit',
  },
  {
    command='view',
    flags=BANG+FILE1+EDITCMD+ARGOPT+TRLBAR,
    func='ex_edit',
  },
  {
    command='vimgrep',
    flags=RANGE+NOTADR+BANG+NEEDARG+EXTRA+NOTRLCOM+TRLBAR+XFILE,
    func='ex_vimgrep',
  },
  {
    command='vimgrepadd',
    flags=RANGE+NOTADR+BANG+NEEDARG+EXTRA+NOTRLCOM+TRLBAR+XFILE,
    func='ex_vimgrep',
  },
  {
    command='viusage',
    flags=TRLBAR,
    func='ex_viusage',
  },
  {
    command='vmap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_map',
  },
  {
    command='vmapclear',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='ex_mapclear',
  },
  {
    command='vmenu',
    flags=RANGE+NOTADR+ZEROR+EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='vnoremap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_map',
  },
  {
    command='vnew',
    flags=BANG+FILE1+RANGE+NOTADR+EDITCMD+ARGOPT+TRLBAR,
    func='ex_splitview',
  },
  {
    command='vnoremenu',
    flags=RANGE+NOTADR+ZEROR+EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='vsplit',
    flags=BANG+FILE1+RANGE+NOTADR+EDITCMD+ARGOPT+TRLBAR,
    func='ex_splitview',
  },
  {
    command='vunmap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_unmap',
  },
  {
    command='vunmenu',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='write',
    flags=RANGE+WHOLEFOLD+BANG+FILE1+ARGOPT+DFLALL+TRLBAR+CMDWIN,
    func='ex_write',
  },
  {
    command='wNext',
    flags=RANGE+WHOLEFOLD+NOTADR+BANG+FILE1+ARGOPT+TRLBAR,
    func='ex_wnext',
  },
  {
    command='wall',
    flags=BANG+TRLBAR+CMDWIN,
    func='do_wqall',
  },
  {
    command='while',
    flags=EXTRA+NOTRLCOM+SBOXOK+CMDWIN,
    func='ex_while',
  },
  {
    command='winsize',
    flags=EXTRA+NEEDARG+TRLBAR,
    func='ex_winsize',
  },
  {
    command='wincmd',
    flags=NEEDARG+WORD1+RANGE+NOTADR,
    func='ex_wincmd',
  },
  {
    command='windo',
    flags=BANG+NEEDARG+EXTRA+NOTRLCOM,
    func='ex_listdo',
  },
  {
    command='winpos',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='ex_winpos',
  },
  {
    command='wnext',
    flags=RANGE+NOTADR+BANG+FILE1+ARGOPT+TRLBAR,
    func='ex_wnext',
  },
  {
    command='wprevious',
    flags=RANGE+NOTADR+BANG+FILE1+ARGOPT+TRLBAR,
    func='ex_wnext',
  },
  {
    command='wq',
    flags=RANGE+WHOLEFOLD+BANG+FILE1+ARGOPT+DFLALL+TRLBAR,
    func='ex_exit',
  },
  {
    command='wqall',
    flags=BANG+FILE1+ARGOPT+DFLALL+TRLBAR,
    func='do_wqall',
  },
  {
    command='wsverb',
    flags=EXTRA+NOTADR+NEEDARG,
    func='ex_wsverb',
  },
  {
    command='wundo',
    flags=BANG+NEEDARG+FILE1,
    func='ex_wundo',
  },
  {
    command='wviminfo',
    flags=BANG+FILE1+TRLBAR+CMDWIN,
    func='ex_viminfo',
  },
  {
    command='xit',
    flags=RANGE+WHOLEFOLD+BANG+FILE1+ARGOPT+DFLALL+TRLBAR+CMDWIN,
    func='ex_exit',
  },
  {
    command='xall',
    flags=BANG+TRLBAR,
    func='do_wqall',
  },
  {
    command='xmap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_map',
  },
  {
    command='xmapclear',
    flags=EXTRA+TRLBAR+CMDWIN,
    func='ex_mapclear',
  },
  {
    command='xmenu',
    flags=RANGE+NOTADR+ZEROR+EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='xnoremap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_map',
  },
  {
    command='xnoremenu',
    flags=RANGE+NOTADR+ZEROR+EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='xunmap',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_unmap',
  },
  {
    command='xunmenu',
    flags=EXTRA+TRLBAR+NOTRLCOM+USECTRLV+CMDWIN,
    func='ex_menu',
  },
  {
    command='yank',
    flags=RANGE+WHOLEFOLD+REGSTR+COUNT+TRLBAR+CMDWIN,
    func='ex_operators',
  },
  {
    command='z',
    flags=RANGE+WHOLEFOLD+EXTRA+EXFLAGS+TRLBAR+CMDWIN,
    func='ex_z',
  },
  {
    command='!',
    enum='CMD_bang',
    flags=RANGE+WHOLEFOLD+BANG+FILES+CMDWIN,
    func='ex_bang',
  },
  {
    command='#',
    enum='CMD_pound',
    flags=RANGE+WHOLEFOLD+COUNT+EXFLAGS+TRLBAR+CMDWIN,
    func='ex_print',
  },
  {
    command='&',
    enum='CMD_and',
    flags=RANGE+WHOLEFOLD+EXTRA+CMDWIN+MODIFY,
    func='do_sub',
  },
  {
    command='*',
    enum='CMD_star',
    flags=RANGE+WHOLEFOLD+EXTRA+TRLBAR+CMDWIN,
    func='ex_at',
  },
  {
    command='<',
    enum='CMD_lshift',
    flags=RANGE+WHOLEFOLD+COUNT+EXFLAGS+TRLBAR+CMDWIN+MODIFY,
    func='ex_operators',
  },
  {
    command='=',
    enum='CMD_equal',
    flags=RANGE+TRLBAR+DFLALL+EXFLAGS+CMDWIN,
    func='ex_equal',
  },
  {
    command='>',
    enum='CMD_rshift',
    flags=RANGE+WHOLEFOLD+COUNT+EXFLAGS+TRLBAR+CMDWIN+MODIFY,
    func='ex_operators',
  },
  {
    command='@',
    enum='CMD_at',
    flags=RANGE+WHOLEFOLD+EXTRA+TRLBAR+CMDWIN,
    func='ex_at',
  },
  {
    command='Next',
    flags=EXTRA+RANGE+NOTADR+COUNT+BANG+EDITCMD+ARGOPT+TRLBAR,
    func='ex_previous',
  },
  {
    command='Print',
    flags=RANGE+WHOLEFOLD+COUNT+EXFLAGS+TRLBAR+CMDWIN,
    func='ex_print',
  },
  {
    command='~',
    enum='CMD_tilde',
    flags=RANGE+WHOLEFOLD+EXTRA+CMDWIN+MODIFY,
    func='do_sub',
  },
}
