local bit = require('bit')

local NONE = 0
local NCH = 0x01
local NCH_NOP = bit.bor(0x02, NCH)
local NCH_ALW = bit.bor(0x04, NCH)
local LANG = 0x08
local SS = 0x10
local SSS = 0x20
local STS = 0x40
local RL = 0x80
local KEEPREG = 0x100
local NCW = 0x200

local SEARCH_REV = 0x01
local BL_WHITE = 1
local BL_FIX = 4

local FORWARD = 1
local BACKWARD = -1

local TRUE = 1

local MSCR_DOWN = 0
local MSCR_UP = 1
local MSCR_LEFT = -1
local MSCR_RIGHT = -2

local module = {}

module.nv_cmds = {
  {
    cmd_char = 'NUL',
    cmd_func = 'nv_error',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'Ctrl_A',
    cmd_func = 'nv_addsub',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'Ctrl_B',
    cmd_func = 'nv_page',
    cmd_flags = STS,
    cmd_arg = BACKWARD,
  },
  {
    cmd_char = 'Ctrl_C',
    cmd_func = 'nv_esc',
    cmd_flags = NONE,
    cmd_arg = TRUE,
  },
  {
    cmd_char = 'Ctrl_D',
    cmd_func = 'nv_halfpage',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'Ctrl_E',
    cmd_func = 'nv_scroll_line',
    cmd_flags = NONE,
    cmd_arg = TRUE,
  },
  {
    cmd_char = 'Ctrl_F',
    cmd_func = 'nv_page',
    cmd_flags = STS,
    cmd_arg = FORWARD,
  },
  {
    cmd_char = 'Ctrl_G',
    cmd_func = 'nv_ctrlg',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'Ctrl_H',
    cmd_func = 'nv_ctrlh',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'Ctrl_I',
    cmd_func = 'nv_pcmark',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'NL',
    cmd_func = 'nv_down',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'Ctrl_K',
    cmd_func = 'nv_error',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'Ctrl_L',
    cmd_func = 'nv_clear',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'CAR',
    cmd_func = 'nv_down',
    cmd_flags = NONE,
    cmd_arg = TRUE,
  },
  {
    cmd_char = 'Ctrl_N',
    cmd_func = 'nv_down',
    cmd_flags = STS,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'Ctrl_O',
    cmd_func = 'nv_ctrlo',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'Ctrl_P',
    cmd_func = 'nv_up',
    cmd_flags = STS,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'Ctrl_Q',
    cmd_func = 'nv_visual',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'Ctrl_R',
    cmd_func = 'nv_redo_or_register',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'Ctrl_S',
    cmd_func = 'nv_ignore',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'Ctrl_T',
    cmd_func = 'nv_tagpop',
    cmd_flags = NCW,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'Ctrl_U',
    cmd_func = 'nv_halfpage',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'Ctrl_V',
    cmd_func = 'nv_visual',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['V']],
    cmd_func = 'nv_visual',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['v']],
    cmd_func = 'nv_visual',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'Ctrl_W',
    cmd_func = 'nv_window',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'Ctrl_X',
    cmd_func = 'nv_addsub',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'Ctrl_Y',
    cmd_func = 'nv_scroll_line',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'Ctrl_Z',
    cmd_func = 'nv_suspend',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'ESC',
    cmd_func = 'nv_esc',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'Ctrl_BSL',
    cmd_func = 'nv_normal',
    cmd_flags = NCH_ALW,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'Ctrl_RSB',
    cmd_func = 'nv_ident',
    cmd_flags = NCW,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'Ctrl_HAT',
    cmd_func = 'nv_hat',
    cmd_flags = NCW,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'Ctrl__',
    cmd_func = 'nv_error',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [[' ']],
    cmd_func = 'nv_right',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['!']],
    cmd_func = 'nv_operator',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['"']],
    cmd_func = 'nv_regname',
    cmd_flags = bit.bor(NCH_NOP, KEEPREG),
    cmd_arg = NONE,
  },
  {
    cmd_char = [['#']],
    cmd_func = 'nv_ident',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['$']],
    cmd_func = 'nv_dollar',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['%']],
    cmd_func = 'nv_percent',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['&']],
    cmd_func = 'nv_optrans',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['\'']],
    cmd_func = 'nv_gomark',
    cmd_flags = NCH_ALW,
    cmd_arg = TRUE,
  },
  {
    cmd_char = [['(']],
    cmd_func = 'nv_brace',
    cmd_flags = NONE,
    cmd_arg = BACKWARD,
  },
  {
    cmd_char = [[')']],
    cmd_func = 'nv_brace',
    cmd_flags = NONE,
    cmd_arg = FORWARD,
  },
  {
    cmd_char = [['*']],
    cmd_func = 'nv_ident',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['+']],
    cmd_func = 'nv_down',
    cmd_flags = NONE,
    cmd_arg = TRUE,
  },
  {
    cmd_char = [[',']],
    cmd_func = 'nv_csearch',
    cmd_flags = NONE,
    cmd_arg = TRUE,
  },
  {
    cmd_char = [['-']],
    cmd_func = 'nv_up',
    cmd_flags = NONE,
    cmd_arg = TRUE,
  },
  {
    cmd_char = [['.']],
    cmd_func = 'nv_dot',
    cmd_flags = KEEPREG,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['/']],
    cmd_func = 'nv_search',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['0']],
    cmd_func = 'nv_beginline',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['1']],
    cmd_func = 'nv_ignore',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['2']],
    cmd_func = 'nv_ignore',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['3']],
    cmd_func = 'nv_ignore',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['4']],
    cmd_func = 'nv_ignore',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['5']],
    cmd_func = 'nv_ignore',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['6']],
    cmd_func = 'nv_ignore',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['7']],
    cmd_func = 'nv_ignore',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['8']],
    cmd_func = 'nv_ignore',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['9']],
    cmd_func = 'nv_ignore',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [[':']],
    cmd_func = 'nv_colon',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [[';']],
    cmd_func = 'nv_csearch',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['<']],
    cmd_func = 'nv_operator',
    cmd_flags = RL,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['=']],
    cmd_func = 'nv_operator',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['>']],
    cmd_func = 'nv_operator',
    cmd_flags = RL,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['?']],
    cmd_func = 'nv_search',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['@']],
    cmd_func = 'nv_at',
    cmd_flags = NCH_NOP,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['A']],
    cmd_func = 'nv_edit',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['B']],
    cmd_func = 'nv_bck_word',
    cmd_flags = NONE,
    cmd_arg = 1,
  },
  {
    cmd_char = [['C']],
    cmd_func = 'nv_abbrev',
    cmd_flags = KEEPREG,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['D']],
    cmd_func = 'nv_abbrev',
    cmd_flags = KEEPREG,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['E']],
    cmd_func = 'nv_wordcmd',
    cmd_flags = NONE,
    cmd_arg = TRUE,
  },
  {
    cmd_char = [['F']],
    cmd_func = 'nv_csearch',
    cmd_flags = bit.bor(NCH_ALW, LANG),
    cmd_arg = BACKWARD,
  },
  {
    cmd_char = [['G']],
    cmd_func = 'nv_goto',
    cmd_flags = NONE,
    cmd_arg = TRUE,
  },
  {
    cmd_char = [['H']],
    cmd_func = 'nv_scroll',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['I']],
    cmd_func = 'nv_edit',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['J']],
    cmd_func = 'nv_join',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['K']],
    cmd_func = 'nv_ident',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['L']],
    cmd_func = 'nv_scroll',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['M']],
    cmd_func = 'nv_scroll',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['N']],
    cmd_func = 'nv_next',
    cmd_flags = NONE,
    cmd_arg = SEARCH_REV,
  },
  {
    cmd_char = [['O']],
    cmd_func = 'nv_open',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['P']],
    cmd_func = 'nv_put',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['Q']],
    cmd_func = 'nv_regreplay',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['R']],
    cmd_func = 'nv_Replace',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['S']],
    cmd_func = 'nv_subst',
    cmd_flags = KEEPREG,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['T']],
    cmd_func = 'nv_csearch',
    cmd_flags = bit.bor(NCH_ALW, LANG),
    cmd_arg = BACKWARD,
  },
  {
    cmd_char = [['U']],
    cmd_func = 'nv_Undo',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['W']],
    cmd_func = 'nv_wordcmd',
    cmd_flags = NONE,
    cmd_arg = TRUE,
  },
  {
    cmd_char = [['X']],
    cmd_func = 'nv_abbrev',
    cmd_flags = KEEPREG,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['Y']],
    cmd_func = 'nv_abbrev',
    cmd_flags = KEEPREG,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['Z']],
    cmd_func = 'nv_Zet',
    cmd_flags = bit.bor(NCH_NOP, NCW),
    cmd_arg = NONE,
  },
  {
    cmd_char = [['[']],
    cmd_func = 'nv_brackets',
    cmd_flags = NCH_ALW,
    cmd_arg = BACKWARD,
  },
  {
    cmd_char = [['\\']],
    cmd_func = 'nv_error',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [[']']],
    cmd_func = 'nv_brackets',
    cmd_flags = NCH_ALW,
    cmd_arg = FORWARD,
  },
  {
    cmd_char = [['^']],
    cmd_func = 'nv_beginline',
    cmd_flags = NONE,
    cmd_arg = bit.bor(BL_WHITE, BL_FIX),
  },
  {
    cmd_char = [['_']],
    cmd_func = 'nv_lineop',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['`']],
    cmd_func = 'nv_gomark',
    cmd_flags = NCH_ALW,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['a']],
    cmd_func = 'nv_edit',
    cmd_flags = NCH,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['b']],
    cmd_func = 'nv_bck_word',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['c']],
    cmd_func = 'nv_operator',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['d']],
    cmd_func = 'nv_operator',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['e']],
    cmd_func = 'nv_wordcmd',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['f']],
    cmd_func = 'nv_csearch',
    cmd_flags = bit.bor(NCH_ALW, LANG),
    cmd_arg = FORWARD,
  },
  {
    cmd_char = [['g']],
    cmd_func = 'nv_g_cmd',
    cmd_flags = NCH_ALW,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['h']],
    cmd_func = 'nv_left',
    cmd_flags = RL,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['i']],
    cmd_func = 'nv_edit',
    cmd_flags = NCH,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['j']],
    cmd_func = 'nv_down',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['k']],
    cmd_func = 'nv_up',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['l']],
    cmd_func = 'nv_right',
    cmd_flags = RL,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['m']],
    cmd_func = 'nv_mark',
    cmd_flags = NCH_NOP,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['n']],
    cmd_func = 'nv_next',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['o']],
    cmd_func = 'nv_open',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['p']],
    cmd_func = 'nv_put',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['q']],
    cmd_func = 'nv_record',
    cmd_flags = NCH,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['r']],
    cmd_func = 'nv_replace',
    cmd_flags = bit.bor(NCH_NOP, LANG),
    cmd_arg = NONE,
  },
  {
    cmd_char = [['s']],
    cmd_func = 'nv_subst',
    cmd_flags = KEEPREG,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['t']],
    cmd_func = 'nv_csearch',
    cmd_flags = bit.bor(NCH_ALW, LANG),
    cmd_arg = FORWARD,
  },
  {
    cmd_char = [['u']],
    cmd_func = 'nv_undo',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['w']],
    cmd_func = 'nv_wordcmd',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['x']],
    cmd_func = 'nv_abbrev',
    cmd_flags = KEEPREG,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['y']],
    cmd_func = 'nv_operator',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['z']],
    cmd_func = 'nv_zet',
    cmd_flags = NCH_ALW,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['{']],
    cmd_func = 'nv_findpar',
    cmd_flags = NONE,
    cmd_arg = BACKWARD,
  },
  {
    cmd_char = [['|']],
    cmd_func = 'nv_pipe',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = [['}']],
    cmd_func = 'nv_findpar',
    cmd_flags = NONE,
    cmd_arg = FORWARD,
  },
  {
    cmd_char = [['~']],
    cmd_func = 'nv_tilde',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  -- pound sign
  {
    cmd_char = 'POUND',
    cmd_func = 'nv_ident',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_MOUSEUP',
    cmd_func = 'nv_mousescroll',
    cmd_flags = NONE,
    cmd_arg = MSCR_UP,
  },
  {
    cmd_char = 'K_MOUSEDOWN',
    cmd_func = 'nv_mousescroll',
    cmd_flags = NONE,
    cmd_arg = MSCR_DOWN,
  },
  {
    cmd_char = 'K_MOUSELEFT',
    cmd_func = 'nv_mousescroll',
    cmd_flags = NONE,
    cmd_arg = MSCR_LEFT,
  },
  {
    cmd_char = 'K_MOUSERIGHT',
    cmd_func = 'nv_mousescroll',
    cmd_flags = NONE,
    cmd_arg = MSCR_RIGHT,
  },
  {
    cmd_char = 'K_LEFTMOUSE',
    cmd_func = 'nv_mouse',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_LEFTMOUSE_NM',
    cmd_func = 'nv_mouse',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_LEFTDRAG',
    cmd_func = 'nv_mouse',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_LEFTRELEASE',
    cmd_func = 'nv_mouse',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_LEFTRELEASE_NM',
    cmd_func = 'nv_mouse',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_MOUSEMOVE',
    cmd_func = 'nv_mouse',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_MIDDLEMOUSE',
    cmd_func = 'nv_mouse',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_MIDDLEDRAG',
    cmd_func = 'nv_mouse',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_MIDDLERELEASE',
    cmd_func = 'nv_mouse',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_RIGHTMOUSE',
    cmd_func = 'nv_mouse',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_RIGHTDRAG',
    cmd_func = 'nv_mouse',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_RIGHTRELEASE',
    cmd_func = 'nv_mouse',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_X1MOUSE',
    cmd_func = 'nv_mouse',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_X1DRAG',
    cmd_func = 'nv_mouse',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_X1RELEASE',
    cmd_func = 'nv_mouse',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_X2MOUSE',
    cmd_func = 'nv_mouse',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_X2DRAG',
    cmd_func = 'nv_mouse',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_X2RELEASE',
    cmd_func = 'nv_mouse',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_IGNORE',
    cmd_func = 'nv_ignore',
    cmd_flags = KEEPREG,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_NOP',
    cmd_func = 'nv_nop',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_INS',
    cmd_func = 'nv_edit',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_KINS',
    cmd_func = 'nv_edit',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_BS',
    cmd_func = 'nv_ctrlh',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_UP',
    cmd_func = 'nv_up',
    cmd_flags = bit.bor(SSS, STS),
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_S_UP',
    cmd_func = 'nv_page',
    cmd_flags = SS,
    cmd_arg = BACKWARD,
  },
  {
    cmd_char = 'K_DOWN',
    cmd_func = 'nv_down',
    cmd_flags = bit.bor(SSS, STS),
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_S_DOWN',
    cmd_func = 'nv_page',
    cmd_flags = SS,
    cmd_arg = FORWARD,
  },
  {
    cmd_char = 'K_LEFT',
    cmd_func = 'nv_left',
    cmd_flags = bit.bor(SSS, STS, RL),
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_S_LEFT',
    cmd_func = 'nv_bck_word',
    cmd_flags = bit.bor(SS, RL),
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_C_LEFT',
    cmd_func = 'nv_bck_word',
    cmd_flags = bit.bor(SSS, RL, STS),
    cmd_arg = TRUE,
  },
  {
    cmd_char = 'K_RIGHT',
    cmd_func = 'nv_right',
    cmd_flags = bit.bor(SSS, STS, RL),
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_S_RIGHT',
    cmd_func = 'nv_wordcmd',
    cmd_flags = bit.bor(SS, RL),
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_C_RIGHT',
    cmd_func = 'nv_wordcmd',
    cmd_flags = bit.bor(SSS, RL, STS),
    cmd_arg = TRUE,
  },
  {
    cmd_char = 'K_PAGEUP',
    cmd_func = 'nv_page',
    cmd_flags = bit.bor(SSS, STS),
    cmd_arg = BACKWARD,
  },
  {
    cmd_char = 'K_KPAGEUP',
    cmd_func = 'nv_page',
    cmd_flags = bit.bor(SSS, STS),
    cmd_arg = BACKWARD,
  },
  {
    cmd_char = 'K_PAGEDOWN',
    cmd_func = 'nv_page',
    cmd_flags = bit.bor(SSS, STS),
    cmd_arg = FORWARD,
  },
  {
    cmd_char = 'K_KPAGEDOWN',
    cmd_func = 'nv_page',
    cmd_flags = bit.bor(SSS, STS),
    cmd_arg = FORWARD,
  },
  {
    cmd_char = 'K_END',
    cmd_func = 'nv_end',
    cmd_flags = bit.bor(SSS, STS),
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_KEND',
    cmd_func = 'nv_end',
    cmd_flags = bit.bor(SSS, STS),
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_S_END',
    cmd_func = 'nv_end',
    cmd_flags = SS,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_C_END',
    cmd_func = 'nv_end',
    cmd_flags = bit.bor(SSS, STS),
    cmd_arg = TRUE,
  },
  {
    cmd_char = 'K_HOME',
    cmd_func = 'nv_home',
    cmd_flags = bit.bor(SSS, STS),
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_KHOME',
    cmd_func = 'nv_home',
    cmd_flags = bit.bor(SSS, STS),
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_S_HOME',
    cmd_func = 'nv_home',
    cmd_flags = SS,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_C_HOME',
    cmd_func = 'nv_goto',
    cmd_flags = bit.bor(SSS, STS),
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_DEL',
    cmd_func = 'nv_abbrev',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_KDEL',
    cmd_func = 'nv_abbrev',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_UNDO',
    cmd_func = 'nv_kundo',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_HELP',
    cmd_func = 'nv_help',
    cmd_flags = NCW,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_F1',
    cmd_func = 'nv_help',
    cmd_flags = NCW,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_XF1',
    cmd_func = 'nv_help',
    cmd_flags = NCW,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_SELECT',
    cmd_func = 'nv_select',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_EVENT',
    cmd_func = 'nv_event',
    cmd_flags = KEEPREG,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_COMMAND',
    cmd_func = 'nv_colon',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
  {
    cmd_char = 'K_LUA',
    cmd_func = 'nv_colon',
    cmd_flags = NONE,
    cmd_arg = NONE,
  },
}

return module
