--[[
DO NOT EDIT
This file is autogenerated
--]]

local ffi = require 'ffi'
ffi.cdef [=[
struct winsize { unsigned short int ws_row; unsigned short int ws_col; unsigned short int ws_xpixel; unsigned short int ws_ypixel; };
enum {TIOCGWINSZ=21523};
extern int ioctl (int __fd, unsigned long int __request, ...) __attribute__ ((__nothrow__ , __leaf__)) ;;
]=]
return ffi.load 'c' --[[@as table]]
