set(UNIBILIUM_CMAKE_ARGS
  -D BUILD_MAN_PAGES=OFF
  -D BUILD_TESTS=OFF
  -D BUILD_TOOLS=OFF)

get_externalproject_options(unibilium ${DEPS_IGNORE_SHA})
ExternalProject_Add(unibilium
  DOWNLOAD_DIR ${DEPS_DOWNLOAD_DIR}/unibilium
  CMAKE_ARGS ${DEPS_CMAKE_ARGS} ${UNIBILIUM_CMAKE_ARGS}
  ${EXTERNALPROJECT_OPTIONS})
