ExternalProject_Add(utf8proc
  URL ${UTF8PROC_URL}
  URL_HASH SHA256=${UTF8PROC_SHA256}
  DOWNLOAD_DIR ${DEPS_DOWNLOAD_DIR}/utf8proc
  CMAKE_ARGS ${DEPS_CMAKE_ARGS}
  CMAKE_CACHE_ARGS ${DEPS_CMAKE_CACHE_ARGS}
  ${EXTERNALPROJECT_OPTIONS})
