---Mapping of image hash  -> sixel image data.
---@type table<string, string>
local HASH_TO_SIXEL_DATA = {}

---Mapping of placement id -> {image, options}.
---@type table<integer, {img:vim.ui.Image, opts:vim.ui.img.Opts, hash:string, redraw:boolean}>
local SIXEL_PLACEMENTS = {}

---Indicates whether or not neovim is running within tmux.
---@type boolean
local IS_TMUX = false

---Used purely to debug output of kitty writing to a terminal.
---@type nil|fun(...:string)
local __debug_write

local _next_id = 0
local function next_id()
  _next_id = _next_id + 1
  return _next_id
end

---Creates a hash unique to an image and parameters that need to be fed to Image Magick.
---This is to be able to cache sixel data generated by Image Magick.
---@param filename string
---@param opts vim.ui.img.Opts
---@return string
local function img_to_hash(filename, opts)
  ---@type string[]
  local items = {
    filename,
    opts.crop and opts.crop:hash() or '',
    opts.size and opts.size:hash() or '',
  }

  return vim.fn.sha256(table.concat(items))
end

---Converts a local image to sixel format using Image Magick.
---@param filename string
---@param opts? vim.ui.img.Opts
---@return string
local function convert_to_sixel(filename, opts)
  opts = opts or {}

  -- Build our command to generate sixel escape codes
  -- 1. Perform a crop first
  -- 2. Resize the cropped image
  -- 3. Output as sixel
  local cmd = { 'magick', 'convert', filename }
  if opts.crop then
    local region = opts.crop:to_pixels()
    table.insert(cmd, '-crop')
    table.insert(
      cmd,
      string.format('%sx%s+%s+%s', region.width, region.height, region.x, region.y)
    )
  end
  if opts.size then
    local size_px = opts.size:to_pixels()
    table.insert(cmd, '-resize')
    table.insert(cmd, string.format('%sx%s', size_px.width, size_px.height))
  end
  table.insert(cmd, 'sixel:-')

  local res = vim.system(cmd):wait()
  assert(res.code == 0, 'failed to convert image to sixel')
  return assert(res.stdout, 'sixel output missing')
end

---Redraws all images managed by sixel provider.
local redraw = require('vim.ui.img.utils').debounce(function()
  local utils = require('vim.ui.img.utils')

  ---@type boolean, string|nil
  local ok, err = pcall(function()
    local writer = utils.new_batch_writer({
      use_chan_send = true,
      write = __debug_write,
    })

    utils.show_cursor(false, writer.write)
    utils.enable_sync_mode(true, writer.write)
    for _, placement in pairs(SIXEL_PLACEMENTS) do
      if placement.redraw then
        placement.redraw = false

        local sixel = HASH_TO_SIXEL_DATA[placement.hash]
        if sixel then
          local pos = placement.opts:position():to_cells()
          utils.move_cursor(pos.x, pos.y, writer.write)
          writer(sixel)
        end
      end
    end
    utils.enable_sync_mode(false, writer.write)
    utils.show_cursor(true, writer.write)

    -- Clear the screen of all sixel images
    vim.cmd.mode()

    writer.flush()
  end)

  if not ok then
    vim.notify(err or 'sixel redraw unknown error', vim.log.levels.WARN)
  end
end, { ms = 5 })

---@param _self vim.ui.img.Provider
---@param ... any
local function load(_self, ...)
  if vim.env['TMUX'] ~= nil then
    local res = vim.system({ 'tmux', 'set', '-p', 'allow-passthrough', 'all' }):wait()
    assert(res.code == 0, 'failed to "set -p allow-passthrough all" for tmux')
    IS_TMUX = true
  end

  -- If debug write function provided, we set it to use globally
  for _, arg in ipairs({ ... }) do
    if type(arg) == 'table' then
      ---@type function
      local debug_write = arg.debug_write
      if type(debug_write) == 'function' then
        __debug_write = debug_write
      end
    end
  end

  vim.api.nvim_create_autocmd({ 'BufWritePost', 'WinScrolled' }, {
    callback = function()
      -- Mark all of our images as needing to be redrawn when scrolling happens
      for _, placement in pairs(SIXEL_PLACEMENTS) do
        placement.redraw = true
      end

      vim.schedule(redraw)
    end,
  })
end

---@param _self vim.ui.img.Provider
local function unload(_self)
  __debug_write = nil
end

---@param _self vim.ui.img.Provider
---@param img vim.ui.Image
---@param opts? vim.ui.img.Opts|{remote?:boolean}
---@return integer
local function show(_self, img, opts)
  opts = opts or {}
  local id = next_id()
  local hash = img_to_hash(img.filename, opts)

  local sixel = HASH_TO_SIXEL_DATA[hash]
  if not sixel then
    sixel = convert_to_sixel(img.filename, opts)
    HASH_TO_SIXEL_DATA[hash] = sixel
  end

  -- Register the new sixel placement and mark it for being drawn
  SIXEL_PLACEMENTS[id] = {
    img = img,
    opts = opts,
    hash = hash,
    redraw = true,
  }

  vim.schedule(redraw)

  return id
end

---@param _self vim.ui.img.Provider
---@param ids integer[]
local function hide(_self, ids)
  -- For all specified sixel placements to be hidden, we just
  -- remove them from our list since they'll be cleared anyway
  for _, id in ipairs(ids) do
    SIXEL_PLACEMENTS[id] = nil
  end

  -- For all remaining sixel placements, we need to redraw them
  -- after the screen is cleared
  for _, placement in pairs(SIXEL_PLACEMENTS) do
    placement.redraw = true
  end

  vim.schedule(redraw)
end

return require('vim.ui.img.providers').new({
  on_load = load,
  on_show = show,
  on_hide = hide,
  on_unload = unload,
})
