#ifndef NVIM_VIML_TESTHELPERS_TRANSLATOR_H
#define NVIM_VIML_TESTHELPERS_TRANSLATOR_H

#ifdef INCLUDE_GENERATED_DECLARATIONS
# include "viml/testhelpers/translator.h"
#endif
#endif  // NVIM_VIML_TESTHELPERS_TRANSLATOR_H
