void set_lang_var(void);
char_u *get_mess_lang(void);
void ex_checktime(exarg_T *eap);
int source_finished(char_u *(*fgetline)(int, void *, int), void *cookie);
void do_finish(exarg_T *eap, int reanimate);
void ex_finish(exarg_T *eap);
void ex_scriptencoding(exarg_T *eap);
void script_line_end(void);
void script_line_exec(void);
void script_line_start(void);
char_u *getsourceline(int c, void *cookie, int indent);
char_u *get_scriptname(scid_T id);
void ex_scriptnames(exarg_T *eap);
int do_source(char_u *fname, int check_other, int is_vimrc);
int source_level(void *cookie);
int *source_dbg_tick(void *cookie);
linenr_T *source_breakpoint(void *cookie);
void ex_source(exarg_T *eap);
void ex_options(exarg_T *eap);
int do_in_runtimepath(char_u *name, int all,
                      void (*callback)(char_u *fname, void *ck),
                      void *cookie);
int source_runtime(char_u *name, int all);
void ex_runtime(exarg_T *eap);
void ex_compiler(exarg_T *eap);
void ex_listdo(exarg_T *eap);
void ex_argdelete(exarg_T *eap);
void ex_argadd(exarg_T *eap);
void ex_argedit(exarg_T *eap);
void ex_next(exarg_T *eap);
void do_argfile(exarg_T *eap, int argn);
void ex_argument(exarg_T *eap);
void ex_last(exarg_T *eap);
void ex_rewind(exarg_T *eap);
void ex_previous(exarg_T *eap);
void ex_args(exarg_T *eap);
void check_arg_idx(win_T *win);
int get_arglist_exp(char_u *str, int *fcountp, char_u ***fnamesp,
                    int wig);
void get_arglist(garray_T *gap, char_u *str);
int buf_write_all(buf_T *buf, int forceit);
int check_fname(void);
int check_changed_any(int hidden);
int can_abandon(buf_T *buf, int forceit);
void dialog_changed(buf_T *buf, int checkall);
int check_changed(buf_T *buf, int flags);
void autowrite_all(void);
int autowrite(buf_T *buf, int forceit);
int prof_def_func(void);
void prof_inchar_exit(void);
void prof_inchar_enter(void);
void script_prof_restore(proftime_T *tm);
void script_prof_save(proftime_T *tm);
void profile_dump(void);
void set_context_in_profile_cmd(expand_T *xp, char_u *arg);
char_u *get_profile_name(expand_T *xp, int idx);
void ex_profile(exarg_T *eap);
int profile_cmp(const proftime_T *tm1, const proftime_T *tm2);
int profile_equal(proftime_T *tm1, proftime_T *tm2);
void profile_sub_wait(proftime_T *tm, proftime_T *tma);
void profile_get_wait(proftime_T *tm);
void profile_self(proftime_T *self, proftime_T *total,
                  proftime_T *children);
void profile_add(proftime_T *tm, proftime_T *tm2);
void profile_divide(proftime_T *tm, int count, proftime_T *tm2);
void profile_zero(proftime_T *tm);
int profile_passed_limit(proftime_T *tm);
void profile_setlimit(long msec, proftime_T *tm);
char *profile_msg(proftime_T *tm);
void profile_sub(proftime_T *tm, proftime_T *tm2);
void profile_end(proftime_T *tm);
void profile_start(proftime_T *tm);
void dbg_breakpoint(char_u *name, linenr_T lnum);
int has_profiling(int file, char_u *fname, int *fp);
linenr_T dbg_find_breakpoint(int file, char_u *fname, linenr_T after);
void ex_breaklist(exarg_T *eap);
void ex_breakdel(exarg_T *eap);
void ex_debuggreedy(exarg_T *eap);
void ex_breakadd(exarg_T *eap);
int dbg_check_skipped(exarg_T *eap);
void dbg_check_breakpoint(exarg_T *eap);
void ex_debug(exarg_T *eap);
void do_debug(char_u *cmd);
void free_scriptnames(void);
char *fgets_cr(char *s, int n, FILE *stream);
void scriptnames_slash_adjust(void);
void ex_language(exarg_T *eap);
void free_locales(void);
char_u *get_lang_arg(expand_T *xp, int idx);
char_u *get_locales(expand_T *xp, int idx);
