static void lrswapbuf(char_u *buf, int len);
static int toF_ending(int c);
static int F_isterm(int c);
static int canF_Rjoin(int c);
static int canF_Ljoin(int c);
static int toF_Rjoin(int c);
static int toF_leading(int c);
static void chg_r_to_Xor_X_(void);
static void chg_l_toXor_X(void);
static void chg_l_to_X_orX_(void);
static void chg_c_to_X_or_X(void);
static void chg_c_to_X_orX_(void);
static void chg_c_toX_orX(void);
static void put_and_redo(int c);
static void put_curr_and_l_to_X(int c);
static int toF_TyB(int c);
static int F_is_TyB_TyC_TyD(int src, int offset);
static int F_is_TyC_TyD(int c);
static int F_is_TyE(int c);
static int toF_Xor_X_(int c);
