char_u *check_map(char_u *keys, int mode, int exact, int ign_mod,
                  int abbr, mapblock_T **mp_ptr,
                  int *local_ptr);
void check_map_keycodes(void);
int put_escstr(FILE *fd, char_u *strstart, int what);
int makemap(FILE *fd, buf_T *buf);
void vim_unescape_csi(char_u *p);
char_u *vim_strsave_escape_csi(char_u *p);
int check_abbr(int c, char_u *ptr, int col, int mincol);
int ExpandMappings(regmatch_T *regmatch, int *num_file, char_u ***file);
char_u *set_context_in_map_cmd(expand_T *xp, char_u *cmd, char_u *arg,
                               int forceit, int isabbrev, int isunmap,
                               cmdidx_T cmdidx);
int map_to_exists_mode(char_u *rhs, int mode, int abbr);
int map_to_exists(char_u *str, char_u *modechars, int abbr);
char_u *map_mode_to_chars(int mode);
void map_clear_int(buf_T *buf, int mode, int local, int abbr);
void map_clear(char_u *cmdp, char_u *arg, int forceit, int abbr);
int get_map_mode(char_u **cmdp, int forceit);
int do_map(int maptype, char_u *arg, int mode, int abbrev);
int input_available(void);
int fix_input_buffer(char_u *buf, int len, int script);
int inchar(char_u *buf, int maxlen, long wait_time, int tb_change_cnt);
void vungetc(int c);
int char_avail(void);
int vpeekc_any(void);
int vpeekc_nomap(void);
int vpeekc(void);
int plain_vgetc(void);
int safe_vgetc(void);
int vgetc(void);
void updatescript(int c);
void before_blocking(void);
int using_script(void);
void openscript(char_u *name, int directly);
void restore_typeahead(tasave_T *tp);
void save_typeahead(tasave_T *tp);
int save_typebuf(void);
void free_typebuf(void);
int alloc_typebuf(void);
void del_typebuf(int len, int offset);
int typebuf_maplen(void);
int typebuf_typed(void);
int typebuf_changed(int tb_change_cnt);
void ins_char_typebuf(int c);
int ins_typebuf(char_u *str, int noremap, int offset, int nottyped,
                int silent);
void stop_redo_ins(void);
int start_redo_ins(void);
int start_redo(long count, int old_redo);
void stuffnumReadbuff(long n);
void stuffcharReadbuff(int c);
void stuffReadbuffSpec(char_u *s);
void stuffReadbuffLen(char_u *s, long len);
void stuffReadbuff(char_u *s);
void AppendNumberToRedobuff(long n);
void AppendCharToRedobuff(int c);
void AppendToRedobuffLit(char_u *str, int len);
void AppendToRedobuff(char_u *s);
void restoreRedobuff(void);
void saveRedobuff(void);
void CancelRedo(void);
void ResetRedobuff(void);
void flush_buffers(int flush_typeahead);
void typeahead_noflush(int c);
int readbuf1_empty(void);
int stuff_empty(void);
char_u *get_inserted(void);
char_u *get_recorded(void);
void free_buff(buffheader_T *buf);
void close_all_scripts(void);
void add_map(char_u *map, int mode);
