static char_u   *eval_map_expr(char_u *str, int c);
static void showmap(mapblock_T *mp, int local);
static void validate_maphash(void);
static void map_free(mapblock_T **);
static int vgetorpeek(int);
static void closescript(void);
static void may_sync_undo(void);
static void gotchars(char_u *, int);
static void init_typebuf(void);
static void copy_redo(int);
static int read_redo(int, int);
static void start_stuff(void);
static int read_readbuf(buffheader_T *buf, int advance);
static int read_readbuffers(int advance);
static void add_char_buff(buffheader_T *, int);
static void add_num_buff(buffheader_T *, long);
static void add_buff(buffheader_T *, char_u *, long n);
static char_u *get_buffcont(buffheader_T *, int);
static bool is_user_input(int k);
