static void check_swap_exists_action(void);
static void main_start_gui(void);
static void source_startup_scripts(mparm_T *parmp);
static void exe_commands(mparm_T *parmp);
static void exe_pre_commands(mparm_T *parmp);
static void edit_buffers(mparm_T *parmp);
static void create_windows(mparm_T *parmp);
static void read_stdin(void);
static void check_tty(mparm_T *parmp);
static void handle_tag(char_u *tagname);
static void handle_quickfix(mparm_T *parmp);
static void load_plugins(void);
static void set_window_layout(mparm_T *parmp);
static char_u* get_fname(mparm_T *parmp);
static void check_and_set_isatty(mparm_T *parmp);
static void allocate_generic_buffers(void);
static void init_startuptime(mparm_T *parmp);
static void init_params(mparm_T *parmp, int argc, char **argv);
static void command_line_scan(mparm_T *parmp);
static void parse_command_name(mparm_T *parmp);
static int get_number_arg(char_u *p, int *idx, int def);
static void usage(void);
static void main_msg(char *s);
static void mainerr(int, char_u *);
static int file_owned(char *fname);
static void time_diff(struct timeval *then, struct timeval *now);
static bool parse_string(char_u **input, char* val, int len);
static bool parse_char_i(char_u **input, char val);
