static int do_swapexists(buf_T *buf, char_u *fname);
static void attention_message(buf_T *buf, char_u *fname);
static void ml_updatechunk(buf_T *buf, long line, long len, int updtype);
static void ml_crypt_prepare(memfile_T *mfp, off_t offset, int reading);
static long char_to_long(char_u *);
static void long_to_char(long, char_u *);
static int fnamecmp_ino(char_u *, char_u *, long);
static int b0_magic_wrong(ZERO_BL *);
static void ml_lineadd(buf_T *, int);
static int ml_add_stack(buf_T *);
static bhdr_T *ml_find_line(buf_T *, linenr_T, int);
static bhdr_T *ml_new_ptr(memfile_T *);
static bhdr_T *ml_new_data(memfile_T *, int, int);
static void ml_flush_line(buf_T *);
static char_u *findswapname(buf_T *, char_u **, char_u *);
static int ml_delete_int(buf_T *, linenr_T, int);
static int ml_append_int(buf_T *, linenr_T, char_u *, colnr_T, int, int);
static int recov_file_names(char_u **, char_u *, int prepend_dot);
static time_t swapfile_info(char_u *);
static void add_b0_fenc(ZERO_BL *b0p, buf_T *buf);
static void set_b0_dir_flag(ZERO_BL *b0p, buf_T *buf);
static void set_b0_fname(ZERO_BL *, buf_T *buf);
static void ml_upd_block0(buf_T *buf, upd_block0_T what);
static int ml_check_b0_id(ZERO_BL *b0p);
static void ml_set_b0_crypt(buf_T *buf, ZERO_BL *b0p);
static char_u *make_percent_swname(char_u *dir, char_u *name);
