void put_time(FILE *fd, time_t the_time);
int put_bytes(FILE *fd, long_u nr, int len);
char_u *read_string(FILE *fd, int cnt);
time_t get8ctime(FILE *fd);
int get4c(FILE *fd);
int get3c(FILE *fd);
int get2c(FILE *fd);
int emsgu(char_u *s, uint64_t n);
int emsgn(char_u *s, int64_t n);
int emsg3(char_u *s, char_u *a1, char_u *a2);
int vim_chdir(char_u *new_dir);
int get_real_state(void);
int call_shell(char_u *cmd, ShellOpts opts, char_u *extra_shell_arg);
int default_fileformat(void);
void set_fileformat(int t, int opt_flags);
int get_fileformat_force(buf_T *buf, exarg_T *eap);
int get_fileformat(buf_T *buf);
int copy_option_part(char_u **option, char_u *buf, int maxlen,
                     char *sep_chars);
int csh_like_shell(void);
int leftcol_changed(void);
void adjust_cursor_col(void);
void check_cursor(void);
void check_cursor_col_win(win_T *win);
void check_cursor_col(void);
void check_cursor_lnum(void);
linenr_T get_cursor_rel_lnum(win_T *wp, linenr_T lnum);
int decl(pos_T *lp);
int dec(pos_T *lp);
int dec_cursor(void);
int incl(pos_T *lp);
int inc(pos_T *lp);
int inc_cursor(void);
int getvpos(pos_T *pos, colnr_T wcol);
int coladvance(colnr_T wcol);
int coladvance_force(colnr_T wcol);
int getviscol2(colnr_T col, colnr_T coladd);
int getviscol(void);
int virtual_active(void);
int illegal_slash(char *name);
int vim_chdirfile(char_u *fname);
