static void get_scroll_overlap(lineoff_T *lp, int dir);
static void max_topfill(void);
static void topline_botline(lineoff_T *lp);
static void botline_topline(lineoff_T *lp);
static void botline_forw(lineoff_T *lp);
static void topline_back(lineoff_T *lp);
static void validate_cheight(void);
static void validate_botline_win(win_T *wp);
static void curs_rows(win_T *wp, int do_botline);
static int check_top_offset(void);
static int scrolljump_value(void);
static void redraw_for_cursorline(win_T *wp);
static void comp_botline(win_T *wp);
