void set_context_in_highlight_cmd(expand_T *xp, char_u *arg);
int highlight_changed(void);
int syn_get_final_id(int hl_id);
int syn_id2attr(int hl_id);
int syn_check_group(char_u *pp, int len);
int syn_namen2id(char_u *linep, int len);
char_u *syn_id2name(int id);
int highlight_exists(char_u *name);
int syn_name2id(char_u *name);
char_u *highlight_color(int id, char_u *what, int modec);
char_u *highlight_has_attr(int id, int flag, int modec);
attrentry_T *syn_cterm_attr2entry(int attr);
attrentry_T *syn_term_attr2entry(int attr);
int syn_attr2attr(int attr);
int hl_combine_attr(int char_attr, int prim_attr);
void clear_hl_tables(void);
void restore_cterm_colors(void);
void do_highlight(char_u *line, int forceit, int init);
int load_colors(char_u *name);
void init_highlight(int both, int reset);
char_u *get_syntime_arg(expand_T *xp, int idx);
void ex_syntime(exarg_T *eap);
int syn_get_foldlevel(win_T *wp, long lnum);
int syn_get_stack_item(int i);
int syn_get_sub_char(void);
int get_syntax_info(int *seqnrp);
int syn_get_id(win_T *wp, long lnum, colnr_T col, int trans,
               int *spellp,
               int keep_state);
char_u *get_syntax_name(expand_T *xp, int idx);
void set_context_in_syntax_cmd(expand_T *xp, char_u *arg);
void set_context_in_echohl_cmd(expand_T *xp, char_u *arg);
void reset_expand_highlight(void);
int syntax_present(win_T *win);
void ex_ownsyntax(exarg_T *eap);
void ex_syntax(exarg_T *eap);
void reset_synblock(win_T *wp);
void syntax_clear(synblock_T *block);
int get_syntax_attr(colnr_T col, int *can_spell, int keep_state);
int syntax_check_changed(linenr_T lnum);
void syntax_end_parsing(linenr_T lnum);
void syn_stack_apply_changes(buf_T *buf);
void syn_stack_free_all(synblock_T *block);
void syntax_start(win_T *wp, linenr_T lnum);
void free_highlight(void);
char_u *get_highlight_name(expand_T *xp, int idx);
attrentry_T *syn_gui_attr2entry(int attr);
char_u *hl_get_font_name(void);
