char_u *translate_mapping(char_u *str, int expmap);
int show_one_termcode(char_u *name, char_u *code, int printit);
void show_termcodes(void);
int find_term_bykeys(char_u *src);
char_u *replace_termcodes(char_u *from, char_u **bufp, int from_part,
                                  int do_lt,
                                  int special);
int check_termcode(int max_offset, char_u *buf, int bufsize,
                           int *buflen);
void del_termcode(char_u *name);
char_u *get_termcode(int i);
char_u *find_termcode(char_u *name);
void add_termcode(char_u *name, char_u *string, int flags);
void clear_termcodes(void);
void scroll_region_reset(void);
void scroll_region_set(win_T *wp, int off);
void term_cursor_shape(void);
void cursor_off(void);
void cursor_on(void);
void scroll_start(void);
int mouse_model_popup(void);
int mouse_has(int c);
void setmouse(void);
int swapping_screen(void);
void may_req_ambiguous_char_width(void);
void may_req_termresponse(void);
void stoptermcap(void);
void starttermcap(void);
void settmode(int tmode);
void set_shellsize(int width, int height, int mustset);
void shell_resized_check(void);
void shell_resized(void);
void win_new_shellsize(void);
void limit_screen_size(void);
void check_shellsize(void);
void ttest(int pairs);
void term_bg_color(int n);
void term_fg_color(int n);
void term_delete_lines(int line_count);
void term_append_lines(int line_count);
void term_cursor_right(int i);
void term_windgoto(int row, int col);
void out_str(char_u *s);
void out_char(unsigned c);
void out_flush_check(void);
void out_flush(void);
void termcapinit(char_u *name);
char_u *tltoa(unsigned long i);
int term_is_8bit(char_u *name);
int add_termcap_entry(char_u *name, int force);
void set_mouse_termcode(int n, char_u *s);
int set_termname(char_u *term);
void set_mouse_topline(win_T *wp);
void term_settitle(char_u *title);
void term_set_winsize(int width, int height);
void term_set_winpos(int x, int y);
void out_str_nf(char_u *s);
void del_mouse_termcode(int n);
void getlinecol(long *cp, long *rp);
