win_T *mouse_find_win(int *rowp, int *colp);
int mouse_comp_pos(win_T *win, int *rowp, int *colp, linenr_T *lnump);
int jump_to_mouse(int flags, int *inclusive, int which_button);
void ui_cursor_shape(void);
void read_error_exit(void);
void ui_breakcheck(void);
void ui_set_shellsize(int mustset);
int ui_get_shellsize(void);
void ui_suspend(void);
void ui_delay(long msec, int ignoreinput);
int ui_char_avail(void);
int ui_inchar(char_u *buf, int maxlen, long wtime, int tb_change_cnt);
void ui_write(char_u *s, int len);
void fill_input_buf(int exit_on_error);
int read_from_input_buf(char_u *buf, long maxlen);
void set_input_buf(char_u *p);
char_u *get_input_buf(void);
int vim_is_input_buf_empty(void);
int vim_is_input_buf_full(void);
void im_save_status(long *psave);
int check_row(int row);
int check_col(int col);
void trash_input_buf(void);
void add_to_input_buf_csi(char_u *str, int len);
void add_to_input_buf(char_u *s, int len);
