#!/bin/bash
set -e -u

FLAVOR=${1:-}

BUILD_DIR=$GITHUB_WORKSPACE/build
BIN_DIR=$GITHUB_WORKSPACE/bin
DEPS_BUILD_DIR=$HOME/nvim-deps
INSTALL_PREFIX=$GITHUB_WORKSPACE/nvim-install
LOG_DIR=$BUILD_DIR/log
NVIM_LOG_FILE=$BUILD_DIR/.nvimlog
VALGRIND_LOG=$LOG_DIR/valgrind-%p.log
CACHE_DIR=$GITHUB_WORKSPACE/.cache
CACHE_UNCRUSTIFY=$CACHE_DIR/uncrustify
CMAKE_FLAGS="-D CI_BUILD=ON -D CMAKE_INSTALL_PREFIX:PATH=$INSTALL_PREFIX -D MIN_LOG_LEVEL=3"
ASAN_OPTIONS=
UBSAN_OPTIONS=
TSAN_OPTIONS=

case "$FLAVOR" in
  asan)
    ASAN_OPTIONS="detect_leaks=1:check_initialization_order=1:handle_abort=1:handle_sigill=1:log_path=$LOG_DIR/asan:intercept_tls_get_addr=0"
    UBSAN_OPTIONS="print_stacktrace=1 log_path=$LOG_DIR/ubsan"
    ;;
  tsan)
    TSAN_OPTIONS=log_path=$LOG_DIR/tsan
    ;;
  uchar)
    CMAKE_FLAGS+=" -D UNSIGNED_CHAR=ON"
    ;;
  functionaltest-lua)
    CMAKE_FLAGS+=" -D PREFER_LUA=ON"
    ;;
  *)
    ;;
esac

cat <<EOF >> "$GITHUB_ENV"
CMAKE_FLAGS=$CMAKE_FLAGS
BUILD_DIR=$BUILD_DIR
BIN_DIR=$BIN_DIR
DEPS_BUILD_DIR=$DEPS_BUILD_DIR
INSTALL_PREFIX=$INSTALL_PREFIX
LOG_DIR=$LOG_DIR
NVIM_LOG_FILE=$NVIM_LOG_FILE
VALGRIND_LOG=$VALGRIND_LOG
CACHE_DIR=$CACHE_DIR
CACHE_UNCRUSTIFY=$CACHE_UNCRUSTIFY
ASAN_OPTIONS=$ASAN_OPTIONS
UBSAN_OPTIONS=$UBSAN_OPTIONS
TSAN_OPTIONS=$TSAN_OPTIONS
EOF

cat <<EOF >> "$GITHUB_PATH"
$BIN_DIR
EOF
