name: "Remove reviewers"
on:
  pull_request_target:
    types: [converted_to_draft, closed]
jobs:
  remove-reviewers:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: 'Remove reviewers'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TEAM_REVIEW }}
          script: |
            const script = require('./.github/scripts/remove-reviewers.js')
            await script({github, context})
