name: "reviewers: remove"
on:
  pull_request_target:
    types: [converted_to_draft, closed]

permissions: {}

jobs:
  remove-reviewers:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: 'Remove reviewers'
        uses: actions/github-script@v9
        with:
          script: |
            const { data } = await github.rest.pulls.listRequestedReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            const reviewers = data.users.map((e) => e.login);

            if (reviewers.length) {
              await github.rest.pulls.removeRequestedReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                reviewers,
              });
            }
