name: test-bsd

on:
  push:
    branches:
      - 'master'
      - 'release-[0-9]+.[0-9]+'
  pull_request:
    branches:
      - 'master'
      - 'release-[0-9]+.[0-9]+'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  freebsd:
    name: FreeBSD
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - name: Build
        uses: vmactions/freebsd-vm@f0552d3b69211736abd97f02ff3d4674c56b73b1 # v1.5.5
        with:
          usesh: true
          cache-after-prepare: true
          prepare: |
            pkg install -y cmake gmake ninja unzip wget gettext python git
          run: |
            set -e
            gmake deps
            gmake CMAKE_EXTRA_FLAGS="-DCI_BUILD=ON" nvim
            ./build/bin/nvim --version

  openbsd:
    name: OpenBSD
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - name: Build
        uses: vmactions/openbsd-vm@86cdc08415d9d0865267e686561e276c52d62530 # v1.4.7
        with:
          usesh: true
          cache-after-prepare: true
          prepare: |
            pkg_add -I cmake gmake ninja gettext-tools gettext-runtime git
          run: |
            set -e
            gmake deps
            gmake CMAKE_EXTRA_FLAGS="-DCI_BUILD=ON" nvim
            ./build/bin/nvim --version
