name: macos-universal
on:
  pull_request:
    branches:
      - 'master'
      - 'release-[0-9]+.[0-9]+'
    paths:
      - '**.cmake'
      - '**/CMakeLists.txt'
      - '**/CMakePresets.json'
      - 'cmake.*/**'
      - '.github/scripts/build_universal_macos.sh'
      - '.github/workflow/universal_macos.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  macos-universal:
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew update --quiet
          brew install automake ninja

      - run: printf 'NVIM_BUILD_TYPE=Release\n' >> $GITHUB_ENV

      - name: Build universal binary
        run: ./.github/scripts/build_universal_macos.sh
